### PR TITLE
feat: Vizzu - Create Animated Bar Chart

### PR DESCRIPTION
**Pull request by jravenel**
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1678

### CODE REVIEW

**Comment by FlorentLvr** [comment]
Hi @alexandre-petit! Hope you are doing well! Just checking, do you need some help on this issue?

**Comment by alexandre-petit** [comment]
Hi @FlorentLvr, thanks for asking,
I did most of the notebook and matched  the structure with the other vizzu templates but I had a few problems when I tryed to edit the notebook in the naas environment.
I couldn't install ipyvizzu to run it, and I had problem to load the data.
For the data, I will probably save the csv file on my github to access it easily.

**Comment by alexandre-petit** [comment]
@FlorentLvr Apparently there were two branches with the same name (1678 and 1679) I will have to pull first to have access to this one and do all the process again

**Comment by FlorentLvr** [comment]
> @FlorentLvr Apparently there were two branches with the same name (1678 and 1679) I will have to pull first to have access to this one and do all the process again

I am not sure to understand. 
In which branch did you work on? It should normally be the one on top of the PR?
Did you work on the branch "1678-vizzu-create-animated-bar-chart"?
1678 is the issue number and 1679 the PR number but normally only one branch is created.

Let me know if you need my help!

image

**Comment by alexandre-petit** [comment]
@FlorentLvr Yes I was working on the 1678. The commit worked but I couldn't push it

**Comment by FlorentLvr** [comment]
> @FlorentLvr Yes I was working on the 1678. The commit worked but I couldn't push it
@alexandre-petit 
ok, did you setup your personal access token and use it to push your work? Are you on our Slack Community? Maybe it will be quicker to resolve this: https://join.slack.com/t/naas-club/shared_invite/zt-1tql56o07-LJNO_~~HQ_w4x1pYVlHBTQ 🙏

**Comment by FlorentLvr** [comment]
@alexandre-petit, thank you for your contribution! 🙏

**Pull request merged**
