### PR TITLE
pie-chart issue

### LINKED ISSUE #2255: Matplotlib - Create Piechart
This notebook will show how to create a piechart with Matplotlib. Pie charts are useful to represent proportions of a whole.

### PR DESCRIPTION
**Pull request by MSaiKiran9**
## Fixes
This PR resolves #2255 

## What does this PR do?
This pr displays a pie-chart for given data

## Screenshots

image

### CODE REVIEW

**Comment by FlorentLvr** [comment]
Hi @MSaiKiran9 , glad you want to contribute!
Unfortunately, we can't validate your PR because you forked our repository instead of cloning it.
Please follow the instructions in the awesome-notebook README.md to start contributing. -> https://github.com/jupyter-naas/awesome-notebooks/blob/master/README.md#how-to-contribute
Let me know if you have any questions! 🙏 
Cheers!

**Comment by FlorentLvr** [comment]
Hi @MSaiKiran9 , glad you want to contribute!
Unfortunately, we can't validate your PR because you forked our repository instead of cloning it.
Please follow the instructions in the awesome-notebook README.md to start contributing. -> https://github.com/jupyter-naas/awesome-notebooks/blob/master/README.md#how-to-contribute
Let me know if you have any questions! 🙏
Cheers!

**Comment by MSaiKiran9** [comment]
Hi @FlorentLvr my bad i didn't know that . After cloning the repo locally and editing the required-file in a new branch can i pr like that ?

**Comment by FlorentLvr** [comment]
> Hi @FlorentLvr my bad i didn't know that . After cloning the repo locally and editing the required-file should i make a new branch and make a pr or should i push to the 2255-matplotlib-create-piechart branch that's already there ?

Hey @MSaiKiran9 , no pb. You can work directly from the branch 2255 and just open a PR when you are done!

**Comment by MSaiKiran9** [comment]
@FlorentLvr i can see that only [Open Source Contributor Program] participants can push the code i just applied for that  hope after that i can pr

**Comment by FlorentLvr** [comment]
> @FlorentLvr i can see that only [Open Source Contributor Program] participants can push the code , I just applied for that hope after approval i can pr !

Amazing! You should have received an invitation by email to join our team! 
Once you accept it, you will be able to contribute following our process! 🙏 


image

**Comment by MSaiKiran9** [comment]
Thanyou @FlorentLvr

**Pull request closed without merging**
