### PR TITLE
Dtale

### PR DESCRIPTION
**Pull request by MinuraPunchihewa**
Added the D-Tale directory meant for visualizing data stored as DataFrames. A single notebook has been added for now, in order to visualize the data in a CSV file by first storing it in a pandas DataFrame and then using the D-Tale package for visualization. This package will allow the user to view the entire contents of a CSV file stored as a DataFrame, perform preprocessing, highlight data, create charts and so much more.

### CODE REVIEW

**Comment by Dr0p42** [comment]
👋 Hello @MinuraPunchihewa,

first, thank you for yout contribution.

I just added to @jupyter-naas/opensource-contributors team. Could you please create a new branch on https://github.com/jupyter-naas/awesome-notebooks and only push this notebook https://github.com/MinuraPunchihewa/awesome-notebooks/blob/dtale/D-Tale/dtale_visualize_csv.ipynb please?

For testing I had to run `! pip install --user dtale` for it to be working, it may be nice to add it as a cell in the inputs maybe?

Great work, d-tale will definitely help us and the community when interacting with dataframes 🚀

**Comment by PeaceBello** [comment]
Alright, I'll get it to it soon.

**Comment by Dr0p42** [comment]
In fast after further testing it seems that it's not able to display d-tale in app.naas.ai.

Did you tried it in app.naas.ai @MinuraPunchihewa ? I tested to render like so `dtale.show(df, notebook=True)` but same I just get a blank screen. I think we need to configure something to allow it to access d-tale backend that seems to be launched.

**Comment by MinuraPunchihewa** [comment]
Hey guys,
I was checking the problem outlined by @Dr0p42 and it looks there is a slight limitation in running D-Tale on hosted notebooks. More information on this is available here,
https://github.com/man-group/dtale/issues/64

I think one possible solution would be to make port 40000 on the naas server viewable. Is that something that can be done?

**Comment by Dr0p42** [comment]
> Hey guys, I was checking the problem outlined by @Dr0p42 and it looks there is a slight limitation in running D-Tale on hosted notebooks. More information on this is available here, [man-group/dtale#64](https://github.com/man-group/dtale/issues/64)
> 
> I think one possible solution would be to make port 40000 on the naas server viewable. Is that something that can be done?

Hello @MinuraPunchihewa, thank you for checking :) I re tested this morning and it seems to work like we can see in this screenshot:

image

By using this notation:
```python
import dtale
import dtale.app as dtale_app

dtale_app.JUPYTER_SERVER_PROXY = True

d = dtale.show(df, notebook=True)
```

We can see that `d._main_url == '/user/maxime@jublou.fr/proxy/40000/dtale/main/1'` so it's effectively using Jupyterlab proxy 🎉

Here is an example where I directly go with my browser on the url:

image


I did not knew about d-tale and it seems awesome, thanks a lot for that.

@FlorentLvr @jravenel you should take a look at this :)

**Comment by Dr0p42** [comment]
@MinuraPunchihewa now that we know it can work, would you be ok to:
- Create a branch on `awesome-notebooks` (you should have the permissions)
- Update your notebook to reflect our findings.
- Open a new pull request?

Looking forward to get this merged 🚀

**Comment by MinuraPunchihewa** [comment]
Yes, for sure @Dr0p42. I will get this done within the day.

**Comment by Dr0p42** [comment]
> Yes, for sure @Dr0p42. I will get this done within the day.

Awesome thank you @MinuraPunchihewa.

Did you already joined our Slack Community? I cannot find you there already. 

If you want to join us: https://app.slack.com/client/T01E5188RNV

We would be happy to see you there.

Enjoy your Friday and week-end ;)

**Comment by MinuraPunchihewa** [comment]
Yes, I will join.
Guys, do I have the correct permissions? I can't seem to push my code,
`remote: Permission to jupyter-naas/awesome-notebooks.git denied to MinuraPunchihewa.`

**Comment by Dr0p42** [comment]
> Yes, I will join. Guys, do I have the correct permissions? I can't seem to push my code, `remote: Permission to jupyter-naas/awesome-notebooks.git denied to MinuraPunchihewa.`

Yes you should have proper permissions: https://github.com/orgs/jupyter-naas/teams/opensource-contributors/members?query=MinuraPunchihewa

On which branch are you trying to push?

**Comment by MinuraPunchihewa** [comment]
@Dr0p42 a new branch that I created called `dtale`.

**Comment by MinuraPunchihewa** [comment]
Sorry @Dr0p42, my fault. There was a problem with the access token I was using. I was able to push the code.

**Comment by MinuraPunchihewa** [comment]
I have created a new pull request,
https://github.com/jupyter-naas/awesome-notebooks/pull/443

I added you as the reviewer, @Dr0p42.

**Comment by Dr0p42** [comment]
Thank you @MinuraPunchihewa , I am closing this one then 👍

**Pull request closed without merging**
