### PR TITLE
1318 GitHub create leaderboard of contributors

### PR DESCRIPTION
**Pull request by SuhasBRao**
Creating a PR, as discussed in the issue, The notebook does not generate a  push link to notion database. It outputs only a dataframe with contributors sorted based on points.

### CODE REVIEW

**Comment by srini047** [comment]
@SuhasBRao A few changes need to be addressed:

- Could you make sure to follow the IMO template provided here: https://github.com/jupyter-naas/awesome-notebooks/blob/master/template.ipynb and restructure the cells accordingly
- Add all the input & output variables in the cells under #inputs #output respectively
- Also do mention the way to get the GitHub access token as every one may not be aware

Please fix these and revert back.

**Comment by SuhasBRao** [comment]
Hey @srini047, Thanks for the review will modify it as required. And get back to you👍

**Comment by SuhasBRao** [comment]
Hey @srini047, I have made the necessary changes, Could you please look into it and let me know if its Okay.

cc: @FlorentLvr

**Review by srini047 — COMMENTED** [review]
@SuhasBRao Very good for the work done till now.

A small addition to the current thing:
- Can you add the no.of PR merged for the particular user as that adds more value to the leaderboard? Do share your views on the same. 

cc: @jravenel @FlorentLvr

**Comment by jravenel** [comment]
> @SuhasBRao Very good for the work done till now.
> 
> A small addition to the current thing:
> 
> * Can you add the no.of PR merged for the particular user as that adds more value to the leaderboard? Do share your views on the same.
> 
> cc: @jravenel @FlorentLvr

@SuhasBRao if it's too much for you to add this for this iteration (until Thursday), we can also open a new issue later and validate this one. Let us know. 

Awesome work :)

**Comment by SuhasBRao** [comment]
> @SuhasBRao Very good for the work done till now.
> 
> A small addition to the current thing:
> 
>     * Can you add the no.of PR merged for the particular user as that adds more value to the leaderboard? Do share your views on the same.
> 
> 
> cc: @jravenel @FlorentLvr

Hey @srini047, I don't think we can get PR merged using GitHub APIs, But can retrieve closed PR's. But that isn't same right. Like a Person can close a PR, and that counts for him in leader board. We must get PR's merged by that User right?

**Comment by FlorentLvr** [comment]
> > @SuhasBRao Very good for the work done till now.
> > A small addition to the current thing:
> > ```
> > * Can you add the no.of PR merged for the particular user as that adds more value to the leaderboard? Do share your views on the same.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > cc: @jravenel @FlorentLvr
> 
> Hey @srini047, I don't think we can get PR merged using GitHub APIs, But can retrieve closed PR's. But that isn't same right. Like a Person can close a PR, and that counts for him in leader board. We must get PR's merged by that User right?

Hi @SuhasBRao, you can get the PR's merged by user, I just checked and you have a key in the json returned named "merged" with a boolean 'true' or 'false'.

I just used this snippet code and will push a new awesome-notebook very soon:

```
# Connect to the GitHub API
g = Github(token)
# Get the repository
repo = g.get_repo(repo_name)
# Get the closed PR
closed_pr = repo.get_pulls(state="closed")
```
image
image

**Comment by FlorentLvr** [comment]
@SuhasBRao, here is the notebook: https://github.com/jupyter-naas/awesome-notebooks/blob/1462-github-get-closed-pr-by-repo/GitHub/GitHub_Get_Closed_PR_by_repo.ipynb

**Comment by srini047** [comment]
@FlorentLvr Then I think lets keep this feature as a next template and will add it as a feature to the Leaderboard. Currently I think we can publish it since this is completely fine.

And later @SuhasBRao can work on adding the PR merge to the leaderboard.

Would like to know your views.

**Comment by FlorentLvr** [comment]
> @FlorentLvr Then I think lets keep this feature as a next template and will add it as a feature to the Leaderboard. Currently I think we can publish it since this is completely fine.
> 
> And later @SuhasBRao can work on adding the PR merge to the leaderboard.
> 
> Would like to know your views.

Sure @srini047 ! I let you merge the PR if you think it is ok!

**Comment by srini047** [comment]
@FlorentLvr @jravenel I think it's wise to merge this PR and get a leaderboard ready. And use PR metrics as an added feature.

**Review by FlorentLvr — APPROVED** [review]

**Comment by FlorentLvr** [comment]
Thank you @SuhasBRao and happy to be first 🥇! @srini047, thank you for review 🙏

**Pull request merged**
