### PR TITLE
Get instagram posts with stats

### PR DESCRIPTION
**Pull request by mohamedabidi97**
Using Instagram graph API to get data of Instagram business account.

### CODE REVIEW

**Comment by FlorentLvr** [comment]
@mohamedabidi97 ! TY for your contribution !
I tried to run your notebook but I didn't understand how to setup my instagram parameters. Could you please provide us more information about that ? You can use markdown cell to explain how to do it as I did as example in the "Setup instagram" section. 
Thanks a lot

**Comment by FlorentLvr** [comment]
Hi @mohamedabidi97 !
As I was saying in our private channel. A video will be very helpfull to understand how to setup this Instagram integration :)
TY very much !

**Comment by mohamedabidi97** [comment]
Hello @Dr0p42,
Glad to hear that from you.
About the token expiration and if we can refresh it or not, let me check the doc of the API and investigate more about that.

**Comment by Dr0p42** [comment]
> Hello @Dr0p42, Glad to hear that from you. About the token expiration and if we can refresh it or not, let me check the doc of the API and investigate more about that.

Hello @mohamedabidi97, maybe this link can help you: https://developers.facebook.com/docs/instagram-basic-display-api/guides/long-lived-access-tokens?locale=en_US

Let me know ;)

**Comment by Dr0p42** [comment]
Hello @mohamedabidi97, a little bump here ;) 

Let us know if you don't have time to finish this PR please so we can handle it somehow 💪

Have a good day :)

**Comment by mohamedabidi97** [comment]
Hello,
I tried once but it didn't work correctly and I'm super busy this period with my internship.
So yes it will be better please and sorry :/

**Pull request merged**
