### PR TITLE
OpenAI - Generate Dialogue

### PR DESCRIPTION
**Pull request by srini047**
Fixes: #1369 

[Demo](https://youtu.be/qQuymF9MiVM)

### CODE REVIEW

**Comment by jravenel** [comment]
Hey @srini047 I see the choice system being a default behavior in the code, can you explain a bit more the reasoning behind it?

**Comment by srini047** [comment]
> Hey @srini047 I see the choice system being a default behavior in the code, can you explain a bit more the reasoning behind it?

@jravenel It looked more intuitive to me because I felt that the user must have the authority to decide whether they need to proceed further or not. Hence I used the variable named `choice` that represents:
- `1` => Continue
- `0` => Stop

Does that make sense?

**Comment by jravenel** [comment]
Yes sure it makes sense. I did not try it just watched the video so I will let you know
What I think about this UX after using. Go job 🥇

**Comment by srini047** [comment]
> Yes sure it makes sense. I did not try it just watched the video so I will let you know
> What I think about this UX after using. Good job 🥇

Cool! Just tried to play with the logic and utilized the power of Jupyter Notebooks.

**Comment by srini047** [comment]
Tagging @FlorentLvr @jravenel

**Comment by FlorentLvr** [comment]
LGTM @srini047! Awesome 💯

**Pull request merged**
