### PR TITLE
feat: Sendgrid - activity feed

### PR DESCRIPTION
**Pull request by SanjuEpic**
Hey @FlorentLvr!
would like to ask you to review an issue that I'm facing currently via filtering emails for getting the stats from sendgrid (related to authorization error)
Here is the issue #53

Thanks!

### CODE REVIEW

**Comment by Dr0p42** [comment]
> Hey @FlorentLvr! would like to ask you to review an issue that I'm facing currently via filtering emails for getting the stats from sendgrid (related to authorization error) Here is the issue #53
> 
> Thanks!

Hello @SanjuEpic, I tried locally (@FlorentLvr  tried as well) and I do have the same error as you. After looking at the documentation [here](https://docs.sendgrid.com/api-reference/e-mail-activity/filter-all-messages) it seems that:
> You must purchase [additional email activity history](https://app.sendgrid.com/settings/billing/addons/email_activity) to gain access to the Email Activity Feed API.

So we just bought it ourselves and it seems that it will take a couple of hours to be active. 

I will keep you posted.

Thank you for your contribution 💪

**Comment by SanjuEpic** [comment]
Great @Dr0p42 and @FlorentLvr !!
Was thinking the same way,
Thank you for letting me know!

**Comment by SanjuEpic** [comment]
Hey @Dr0p42!
Can you let me know how to access this email API (if there are any specific options to tweak)

Currently getting the error "BadRequestsError: HTTP Error 400: Bad Request"
while executing the Sendgrid Get activity feed notebook

error

Thanks!

**Comment by SanjuEpic** [comment]
Any help regarding this step would be appreciated
@Dr0p42  do let me know about the API access credentials if any are required for the one in which the purchase was made.

Thanks!

**Comment by SanjuEpic** [comment]
I have got to know some information regarding the SendGrid API
Have a look at this [comment](https://github.com/sendgrid/sendgrid-ruby/issues/454#issuecomment-1075133933)

Even when I tried with the URL in no encoded fashion, still I was getting the error but with a different message
"InternalServerError: HTTP Error 500: Internal Server Error" and that too it takes some time (about 1 min of execution for this cell)

Possible debug options:
1. Get the right from email to filter i.e the mail id that is used for authorizing the sendgrid app at the time of purchase of the email activity feed API and then debug

Any suggestions are welcome
Thanks!
server_error

**Comment by jravenel** [comment]
The comment is in the Ruby version of the API no ? Same for python ?

**Comment by SanjuEpic** [comment]
Yeah I tried it but no results I have got with respect to python. :(

**Comment by FlorentLvr** [comment]
> Yeah I tried it but no results I have got with respect to python. :(

I used requests library to get all messages and it's working now. Could you please confirm on your side too ? :)

**Comment by SanjuEpic** [comment]
Okay, that's a great help for this issue, will have a look @FlorentLvr.
Thanks!

**Comment by Dr0p42** [comment]
Sorry @SanjuEpic I got sidetracked a loooot. Let me know if you need help on this one ;)

**Comment by SanjuEpic** [comment]
Sure will let you know @Dr0p42
Thanks

**Comment by SanjuEpic** [comment]
I have gone through the code @FlorentLvr, it's running on my side as well.
We can merge this PR now!
Thanks for the help!

**Review by Dr0p42 — APPROVED** [review]
Well done @SanjuEpic 👏

Thank you for this contribution :)

**Pull request merged**
