### PR TITLE
1201 python convert png images to jpg

### LINKED ISSUE #1201: Python - Convert PNG images to JPG
example → https://www.airplane.dev/blog/12-useful-python-scripts-for-developers to be templated using [Naas template framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository) for production use.

### PR DESCRIPTION
**Pull request by devgenix**
Create notebook for converting PNG images to JPG in Python.

If successfully merged, this closes #1201

### CODE REVIEW

**Comment by devgenix** [comment]
@jravenel Please review.

**Review by jravenel — COMMENTED** [review]
added a web URL link for easy testing

**Comment by devgenix** [comment]
> added a web URL link for easy testing

You mean I should add a web URL?

**Comment by jravenel** [comment]
> > added a web URL link for easy testing
> 
> You mean I should add a web URL?

Hey @devgenix yes sorry, my message was sent but not complete.
The reasoning is: for anyone to be able to test/use without being dependent on local drive, we always try to put input asset links that are accessible via internet.
Hence I would suggest we add a subsection in ## Input we can call "Declare file path" with a PATH = "https://en.wikipedia.org/wiki/Portable_Network_Graphics#/media/Fichier:PNG_transparency_demonstration_1.png"  for example and in ## Output put save function directly to local drive. 

Is it more clear? :)

**Comment by devgenix** [comment]
@jravenel yes it is. Thank you.

**Comment by FlorentLvr** [comment]
@devgenix ! Thanks for your contribution! 
Just rework the structure on the input section to be able to set the image input and output path.
I tried with 2 png files and I received those errors below.
Please find attached the 2 images.
Let me know if you have any question 🙏 

image
image

image1
image2

**Comment by FlorentLvr** [comment]
> @devgenix ! Thanks for your contribution! Just rework the structure on the input section to be able to set the image input and output path. I tried with 2 png files and I received those errors below. Please find attached the 2 images. Let me know if you have any question 🙏
> 
> image image
> 
> image1 image2

Hey @devgenix! Just checking out! Let me know if you need my help :)

**Comment by devgenix** [comment]
> > @devgenix ! Thanks for your contribution! Just rework the structure on the input section to be able to set the image input and output path. I tried with 2 png files and I received those errors below. Please find attached the 2 images. Let me know if you have any question 🙏
> > 
> > image image
> > 
> > image1 image2
> 
> Hey @devgenix! Just checking out! Let me know if you need my help :)

I'll rework on it and resubmit it.

**Comment by jravenel** [comment]
HI @devgenix let us know if you need help ;)

**Comment by FlorentLvr** [comment]
@devgenix, hope you are doing well! Just checking out! Let us know if you need help 👍

**Comment by FlorentLvr** [comment]
Hi @devgenix, hope you are doing well! Do you need help with your PR?

**Comment by FlorentLvr** [comment]
Hi @devgenix, 
Hope you are doing well! 
As this PR did not change for the last 21 days, I will close it and reassign the issue to someone else.
If the issue is not reassigned and you want to finish it, you can still work on your branch and reopen this PR! 
I will be happy to review it :) 🙏

**Pull request closed without merging**
