### PR TITLE
Python - PowerPoint Create a Report Presentation

### PR DESCRIPTION
**Pull request by ayoub-berdeddouch**
@FlorentLvr please check it!

### CODE REVIEW

**Comment by FlorentLvr** [comment]
@ayoub-berdeddouch! TY for your contribution! 👍 
It's great but the only thing is that we have to download logos and upload them to Naas. 
Do you think you can create a function to download logos directly from URLs?
In this way, we won't have to do anything to set up the notebook 🙏 
Let me know if you have more questions!

**Comment by ayoub-berdeddouch** [comment]
With pleasure @FlorentLvr!
Yes, sure I will create a function to download the logo by just pasting the URL.
As forThe folder I taught, it was generated with Python so that's why I put it there.

**Comment by ayoub-berdeddouch** [comment]
@FlorentLvr check the new update and let me know if you have any suggestions.

**Comment by FlorentLvr** [comment]
@ayoub-berdeddouch! TY for your contribution! 👍 🙏 
As mentioned in my last commit, I made some changes to improve your notebook readability regarding our IMO framework:
INPUT
- All libraries are imported in the input section
- Variables should be declared on the input section (like outputs name, title, etc...) to make it easy for anyone to setup this notebook
MODEL
- You created one cell per slide which is good so I just added a markdown above to explain what you did.
OUTPUT
- I added a naas.asset.add() to make it easier to download the PowerPoint presentation.
I am looking forward to your next contribution! You did a great job. 💯

**Pull request merged**
