### PR TITLE
feat: Python - Unit converter

### PR DESCRIPTION
**Pull request by Benjifilly**
This one is a bit long, but it works well

### CODE REVIEW

**Comment by FlorentLvr** [comment]
@Benjifilly ! That's a nice one! Do you think you could create one by units? It could interesting to have a template like: "Python - Convert speed units" / "Python - Convert temperature units"

**Comment by Benjifilly** [comment]
Of course I could, but now that you've merged it. But it's not impossible. Would you like me to create one per unit?

**Comment by FlorentLvr** [comment]
> Of course I could, but now that you've merged it. But it's not impossible. Would you like me to create one per unit?

Yes, you can create a new issue like: "Python - Convert multiples units" and create all the notebooks on the same branch.  Is that clear for you?

**Comment by Benjifilly** [comment]
yes, but then how to do with the one already merged ?

**Comment by FlorentLvr** [comment]
> yes, but then how to do with the one already merged ?

You can duplicate it and keep the one the gather every units.
You just have to create new ones.

**Comment by Benjifilly** [comment]
ok np

**Pull request merged**
