### PR TITLE
feat: OpenAI - Prompt template for ChatGPT to act as a world-class business coach

### PR DESCRIPTION
**Pull request by makingsurgeon**
This will close https://github.com/jupyter-naas/awesome-notebooks/issues/2206.

### CODE REVIEW

**Comment by FlorentLvr** [comment]
Hi @makingsurgeon! Thank you for your contribution!

I've updated your template to include a function that creates the driver json. This will help to reduce the number of lines of code. Please ensure you're using the latest version of naas_drivers to utilize the naas_chat_plugin.create() function.

Upon testing your chat plugin, I only received "Yup". Is there something I might have missed? Please let me know if there's any additional information or instructions I should know. Thanks!

image

**Comment by FlorentLvr** [comment]
> @FlorentLvr I'm out of credits right now, so I can't really test this.

@makingsurgeon, just checked your credits and you should have 100. Could you please check it again?

**Comment by makingsurgeon** [comment]
@FlorentLvr I tried to change the link to open the notebook in chatgpt, but it does not work. If I change the link to open it in Jupyter Lab, it works though. I don't know the reason because I basically copy-pasted Jeremy's template.

**Comment by FlorentLvr** [comment]
@makingsurgeon, I work on a template to help you to create your own "Act as a", I merged the branch I was working on into your branch. Could you please pull and used the template: "OpenAI/OpenAI_Create_Act_as_plugin.ipynb" ?

**Comment by makingsurgeon** [comment]
@FlorentLvr I have used the template and updated the files.

**Comment by FlorentLvr** [comment]
> @FlorentLvr I have used the template and updated the files.

@makingsurgeon, did you try your plugin in the naas chat? I still received the answer "Yup". I made some changes, please pull the branch before updating it.
Let me know if you need more help!
image

**Comment by FlorentLvr** [comment]
Hi @makingsurgeon, it appears to be functioning correctly now. However, I was surprised to see placeholders like "[PRODUCT]" in the text. Would it be more appropriate to avoid such keywords in a standard text?

Also, can you pull the last version. Last time, you didn't do it so I had commit again my changes. TY 🙏 

image

**Comment by makingsurgeon** [comment]
@FlorentLvr I hope this fixes everything.

**Comment by FlorentLvr** [comment]
@makingsurgeon, thank you for your contribution! You can now start using it in your Naas Chat. :)

**Pull request merged**
