### PR TITLE
1st commit on Merging

### PR DESCRIPTION
**Pull request by OketunjiOludolapo**
Hi, Jey. This is the notebook on how to merge datasets.

### CODE REVIEW

**Comment by jravenel** [comment]
Hello @OketunjiOludolapo, I just checked your PR. 

My feedbacks: 
- Input section ✅
- Model/Output section : 
--  We need 2 separate sections and document better in text what are the options in the model (1/ pd.merge 2/ pd.concat) and in which cases to use them. 
-- Capital letters are not very easy to read
-- What is in comment should mostly be in Markdown 
-- I would sugget to name the output dataframe df_merge or df_concat 


Let's talk about it on Monday during the community call? @OketunjiOludolapo @FlorentLvr 


FYI @khuyentran1401

**Comment by FlorentLvr** [comment]
Hi @OketunjiOludolapo,
We just reviewed your notebook. Please let us if it's clear for you. 
If you have any question, feel free to ask or join us in our next community call.

**Comment by OketunjiOludolapo** [comment]
> Hi @OketunjiOludolapo,
> 
> Thank you for your work.
> 
> We just reviewed your notebook :
> 
> * We rework the design to make it more simple to understand (rename of sections)
> * We add new category (Other) at the end to show the other use cases you have done.
> * We remove "pd.concat" because we think it would be better to present it in another notebook.
> 
> Please let us if it's clear for you.
> If you have any question, feel free to ask or join us in our next community call.

It's clear and okay.

**Comment by FlorentLvr** [comment]
@OketunjiOludolapo , just validated your PR ! Congratulation !

**Pull request merged**
