### PR TITLE
feat: Dash - Create plot based on owid's oil consumption data

### PR DESCRIPTION
**Pull request by makingsurgeon**
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1889

### CODE REVIEW

**Comment by makingsurgeon** [comment]
@jravenel I have updated the notebook and put it in the new OWID folder.

**Comment by jravenel** [comment]
The action verb should be "Visualize" not visualizing to follow framework pattern + one file only should be in the commit, I currently see 2. Can you update please?

**Comment by makingsurgeon** [comment]
I think I'll close this PR and open a new one.

**Comment by jravenel** [comment]
As you want

**Pull request closed without merging**
