### PR TITLE
feat: add tiktok trending song

### LINKED ISSUE #2543: TikTok - Analyze Songs used on Keywords Trends
**Describe the problem you are facing**
It's quite a task to stay on top of the dynamic [TREND_KEYWORD == Afrobeat] on TikTok. Manually tracking which songs and artists are trending each day is time-consuming and can lead to missed opportunities for engagement and content creation.

**Describe the solution you'd like**
I envision a tool that does the following:
- Input: Automatically pulls daily data on trending TREND_KEYWORD tracks from TikTok.
- Model: Processes and structures the data efficiently following the ABI datamodel
- Output: Delivers a daily updated, easy-to-read data table showcasing trending songs, artists, and key performance metrics.

**ABI Content Table Data Model**

**ENTITY:** Refers to the specific entity being discussed, usually the song or artist.

**SCENARIO:** The context in which the data was collected, e.g., 'Trending Afrobeat Songs on TikTok'.

**SOURCE:** The platform from which the data is sourced, in this scenario, 'TikTok'.

**PUBLISHED_DATE:** The original date the content was posted.

**DATE & TIME:** The date and time when the data was extracted.

**ID:** Unique identifier for the content.

**TITLE:** Title of the TikTok video or content.

**TEXT:** Description or text content associated with the TikTok post.

**CONCEPT:** The main idea or theme identified in the content.

**SENTIMENT:** The general sentiment (positive, neutral, negative) derived from the content.

**TARGET:** The target audience or demographic of the content.

**OBJECTIVE:** The intended goal of the content creator.

**VIEWS, LIKES, COMMENTS, SHARES, ENGAGEMENTS:** Metrics indicating the performance and reach of the content.

**ENGAGEMENT_SCORE:** A derived metric to quantify overall engagement.

**TYPE:** The type of content (video, image, text).

**AUTHOR_NAME:** Name of the content creator.

**AUTHOR_URL:** URL to the content creator's TikTok profile.

**LENGTH:** Duration of the TikTok video.

**PEOPLE_MENTIONED:** Names of people mentioned in the content.

**ORGANIZATION_MENTIONED:** Names of any organizations mentioned.

**CONTENT_TITLE_SHARED:** Title of any shared content within the post.

**CONTENT_URL_SHARED:** URLs to any shared content.

**LINKEDIN_LINKS:** Links to LinkedIn profiles or content if mentioned.

**IMAGE_SHARED:** Any images shared in the post.

**TAGS:** Hashtags or tags associated with the content.

**URL:** Direct URL to the TikTok post.

**DATE_EXTRACT:** The date on which the data was extracted for analysis.

**SCENARIO_ORDER:** The order or sequence of the content within the given scenario.

Time to turn this blueprint into reality and see what stories the data tells us! 

**Additional context**
This tool is for social media strategists and content creators who need to tap into the pulse of trending TikTok music.

### PR DESCRIPTION
**Pull request by alexnodeland**
## Fixes

This PR resolves #2543

## What does this PR do?
Provide a script that allows the user to get the top n trending songs on TikTok, for a given keyword

### CODE REVIEW

**Comment by alexnodeland** [comment]
Added music-specific attributes to the data model:

- `MUSIC_NAME` - The name of the track.
- `MUSIC_AUTHOR` - The author of the track.
- `MUSIC_ORIGINAL` - Indicates if the music is original. (1=TRUE)
- `MUSIC_ALBUM` - The album of the track.
- `MUSIC_PLAY_URL` - The URL to play the music (missing in many cases)
- `MUSIC_COVER_MEDIUM_URL` - The URL of the medium-sized cover image of the music.
- `MUSIC_ID` - The unique identifier of the track on TikTok.

**Comment by FlorentLvr** [comment]
@alexnodeland, TY for your contribution! I will review it today :)

**Comment by alexnodeland** [comment]
> @alexnodeland, TY for your contribution! I will review it today :)

Awesome! Please let me know if you have any questions / change requests, and I'll be happy to address them 😄

**Comment by alexnodeland** [comment]
> @alexnodeland, I encountered this error while running the function in the output section: "An error occurred while running the actor: You must rent a paid Actor in order to run it." I am trying to figure it out. Any ideas?

Hey @FlorentLvr, I believe that you must to add the actor to your Apify account ("rent it") to be able to use it. You could add it with the "Try for Free" button here

https://apify.com/clockworks/tiktok-scraper

**Comment by FlorentLvr** [comment]
@alexnodeland TY for your contribution! Following our discussion, I improved the description with links to how to rent actors and made other minor changes 🙏

**Comment by alexnodeland** [comment]
@FlorentLvr good call! Happy to see this merged!! 😃

**Pull request merged**
