### PR TITLE
Twitter-get-members-of-list-of-particular-user

### PR DESCRIPTION
**Pull request by kaushalkrishna2000**
Hello @FlorentLvr I have made the notebook kindly review it.
The issue is #1347 (Twitter-get-members-of-list-by-user)
Thanks.

### CODE REVIEW

**Comment by Dr0p42** [comment]
No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by kaushalkrishna2000** [comment]
Hello @FlorentLvr I have included some more pointers as to how to apply for bearer token , extract the username , and precautions for the list.

Kindly review it.

Thanks

**Comment by FlorentLvr** [comment]
> Hello @FlorentLvr I have included some more pointers as to how to apply for bearer token , extract the username , and precautions for the list.
> 
> Kindly review it.
> 
> Thanks

@kaushalkrishna2000, TY for your contribution 🙏. It's working well! 
I just checked there were possibilities to manage List members. Maybe, I could be great to have notebooks to add and remove members. What do you think?

https://developer.twitter.com/en/docs/twitter-api/lists/list-members/introduction

**Comment by kaushalkrishna2000** [comment]
I think we can work on that.

**Comment by FlorentLvr** [comment]
> @FlorentLvr I think we can work on that.

💯 Amazing, just assign you to the new issues:
- https://github.com/jupyter-naas/awesome-notebooks/issues/1357
- https://github.com/jupyter-naas/awesome-notebooks/issues/1358

**Pull request merged**
