### PR TITLE
feat: Gsheets to MongoDB automation

### PR DESCRIPTION
**Pull request by OketunjiOludolapo**
How about this version @Dr0p42

### CODE REVIEW

**Comment by FlorentLvr** [comment]
Hi @OketunjiOludolapo ! TY for your contribution. 
I just move all your variables on the "input" section for your notebook  "MongoDB to Google Sheet". In this way, the end will only have to change the variable on top and execute all cells. This make it easier to use. Do you agree ?
Your other contribution was not in the right folder (GitHub instead of Gsheet). Could you please update it following the same framework as the first one ? 
Thanks a lot :)

**Comment by OketunjiOludolapo** [comment]
Thanks @FlorentLvr 
That makes sense so that the code are executed in an orderly manner.
I will make the appropriate changes as well

**Comment by OketunjiOludolapo** [comment]
@FlorentLvr ,I've been trying to push the changes to both files but it's failing. How do i handle that? or should i just create a new branch?

**Comment by FlorentLvr** [comment]
> @FlorentLvr ,I've been trying to push the changes to both files but it's failing. How do i handle that? or should i just create a new branch?

@OketunjiOludolapo, did you pull your branch before working on it ?

**Comment by OketunjiOludolapo** [comment]
> > @FlorentLvr ,I've been trying to push the changes to both files but it's failing. How do i handle that? or should i just create a new branch?
> 
> @OketunjiOludolapo, did you pull your branch before working on it ?

I had to work through the git terminal to resolve the issue but i've pushed it now. Do take a look. Thanks

**Comment by FlorentLvr** [comment]
@OketunjiOludolapo, I removed the transformation dataframe > dict > dataframe and it works perfectly. 
Unfortunately, I can not merge your PR because you started from on old version of master. I will close this branch and open a new one and update your 2 files in there to be easier.

**Pull request closed without merging**
