### PR TITLE
Add Windsor data api dashboard notebook

### PR DESCRIPTION
**Pull request by eliasdabbas**
Initial notebook for the API dashboard.
Ref issue #1264

### CODE REVIEW

**Comment by Dr0p42** [comment]
No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by jravenel** [comment]
Hey @eliasdabbas just checked and it seems a few checks are not passing. 
The notebook does not follow the convention we apply to the rest of the catalog. Do you mind looking at the code and making some changes to make it work? Do you need my help?

Screenshot 2022-10-29 at 19 20 06

**Comment by Dr0p42** [comment]
Hello @eliasdabbas @jravenel here is the link to access the Dashboard: https://dashboard.windsor-ai.kn.naas.ai/

**Comment by eliasdabbas** [comment]
@Dr0p42 Thanks a lot!
Looks good, and runs smooth. I tried it a few times, and had no issues.

**Pull request merged**
