### PR TITLE
Feat. Generate Leads from LinkedIN

### PR DESCRIPTION
**Pull request by calok64**
Added method - "get_linkedin_columns" to create dataframe for common data model

### CODE REVIEW

**Comment by calok64** [comment]
@Dr0p42 have added method to create common data model. Please review.

@jravenel @FlorentLvr We can now try to merge notebooks for LinkedIN, Twitter and TikTok to check if we are getting proper output 

@megha2907 @RiddhiDeshpande222

**Comment by Dr0p42** [comment]
@FlorentLvr I will let you review this one ;)

**Comment by FlorentLvr** [comment]
@calok64 , for this update ! I just changed the formula to get posts feed (count=1) to avoid misunderstanding about getting the correct date from LinkedIn post.

**Comment by jravenel** [comment]
> @calok64 , for this update ! I just changed the formula to get posts feed (count=1) to avoid misunderstanding about getting the correct date from LinkedIn post. It would be amazing if you could add a video explaining how you setup and run this notebook (starting with the outputs) because it can be a usefull tool for sales. Do you think it would be possible for you to do that ? Thanks a lot :)

@calok64 hey Alok, can you help by making a demo of how it works? It's not easy to use and validate otherwise! Thanks a lot.

**Comment by calok64** [comment]
@jravenel sure will make a demo of the notebook and share

**Comment by FlorentLvr** [comment]
Hi @calok64,
Hope you are doing well!
I will close this PR because we can't test it with your demo yet. 
I think we will develop a data product to generate leads from LinkedIn. 
Let me know if you want to be involved :).
Have a good day!

**Comment by calok64** [comment]
@FlorentLvr yes interested to be in that task

**Pull request closed without merging**
