### PR TITLE
Yahoo Finance - Get Brent Crud Oil trend and predictions

### PR DESCRIPTION
**Pull request by ayoub-berdeddouch**
@jravenel @FlorentLvr, check it first then I will iterate on it I will use other models from Pycaret or Statsmodels, FbProphet!

### CODE REVIEW

**Comment by jravenel** [comment]
Hey @ayoub-berdeddouch thanks a lot for the contribution, I worked on the notebook and tweaked a few things.
- rename title and name of file to be mode explicit
- fix indentation issues
- change tags for better indexing (added oil, petrol...)
- change description for better indexing
- added a NAME variable to a more explicit display in the chart
- change timeframe to get a 1y timeframe with -9 months actual and +3 months predictions
- added disclaimer
- deleted candlestick as not a lot people can actually read it
- reformated the output to save to excel, png, html

This way we have a boilerplate that we can use for other tickers from YahooFinance and the contributor can focus on the model itseft. 

Can you have a look? What do you think?

**Comment by ayoub-berdeddouch** [comment]
@jravenel  it looks neat! thank you! 
I need to check the IMO just in case next time don't get Lint Errors.

Thats great we can now iterate on it!

**Comment by jravenel** [comment]
Cool ! Let me merge this, and then we can create a new issue to improve the quality of the model.

**Comment by ayoub-berdeddouch** [comment]
Perfect! Sure looking forward to it!

**Pull request merged**
