### PR TITLE
feat: Google Calendar - List events from calendar

### PR DESCRIPTION
**Pull request by FlorentLvr**
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1600

### CODE REVIEW

**Comment by srini047** [comment]
Video: [Loom](https://www.loom.com/share/edc1d1aba3c74b2085e664243fb25690)

@FlorentLvr

**Comment by srini047** [comment]
> > Video: [Loom](https://www.loom.com/share/edc1d1aba3c74b2085e664243fb25690)
> > @FlorentLvr
> 
> Hey @srini047! TY for the video! I try to test the template but i did not have the secret.json file. Can you add a procedure to explain how we can get it? 🙏

Added the procedure to obtain `secrets.json` file

**Comment by FlorentLvr** [comment]
Let's check your PR during our meeting this week ! :)

**Comment by FlorentLvr** [comment]
LGTM 🚀 @srini047

**Pull request merged**
