### PR TITLE
1815 advertools audit robots txt and xml sitemap issues

### PR DESCRIPTION
**Pull request by eliasdabbas**
Creates notebook for #1815

### CODE REVIEW

**Comment by Dr0p42** [comment]
No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by FlorentLvr** [comment]
Hi @eliasdabbas, I just tested your notebook and it is working well! Thank you for your contribution again 🙏 @jravenel

**Comment by eliasdabbas** [comment]
Thanks a lot @FlorentLvr very happy to see this merged!

Here are some minor changes that I think can improve the notebook. Should I create a separate issue/pull request for them, or what's the best approach? 
Here are my suggested changes, so you can also review them:



1. Since there is usage of the `sitemap_to_df` function, and it has various options, maybe add a link to it in the references section?

[advertools XML sitemaps](https://advertools.readthedocs.io/en/master/advertools.sitemaps.html)



2. Remove the following lines:

```python
# just for testing:
robotstxt_url = "https://www.google.com/robots.txt"
```

3. Split into two cells, the cell that starts with  `# Get users agent`, with the first cell being: 

```python
# Get users agent
user_agents = robots_df[robots_df['directive'].str.contains('user-agent', case=False)]['content']
user_agents
```

**Comment by FlorentLvr** [comment]
@eliasdabbas, just created a new issue here: https://github.com/jupyter-naas/awesome-notebooks/issues/1821

**Pull request merged**
