### PR TITLE
feat: use github driver function to get commits + rework notebook

### PR DESCRIPTION
**Pull request by FlorentLvr**

### CODE REVIEW

**Comment by FlorentLvr** [comment]
@SanjuEpic , I created a github driver to abstract the "get_commits" function and i made some adjustements on the notebook. 
Could you please review my code ?
You can also have a look at the github driver. 
This is something you should be able to do after submitted your notebook.
We could discuss later about it for sure.
Have a great day. 
TY

**Comment by SanjuEpic** [comment]
Sure will go through it on Monday 👍

**Comment by FlorentLvr** [comment]
@SanjuEpic , i have made some changes regarding the graph and created new notebook to get the ranking by user. Could you please have a look at it and let me know if it's ok on your side ! TY

**Comment by SanjuEpic** [comment]
Great to go @FlorentLvr!
Went through both the notebooks. All code looks good and is very informative.
We can now merge this PR

**Review by SanjuEpic — APPROVED** [review]
Good to go with the notebook.

**Pull request merged**
