### PR TITLE
feat: track issues on roadmap

### PR DESCRIPTION
**Pull request by SanjuEpic**
Hi @FlorentLvr!
This is the PR created for the issue referring to #322 

Still collecting and creating a notebook on Stale PR's is left.
Would work on it soon
Thanks!

### CODE REVIEW

**Comment by FlorentLvr** [comment]
@SanjuEpic , well done ! It's working well 👍
Please below my reviews:

- Could you please use this url  "https://github.com/orgs/jupyter-naas/projects" instead of "https://api.github.com/orgs/jupyter-naas/projects"

- The first function : get_active_project() could be a notebook by itself. Could you please create it ? 
> Input: url + token
> Model: Function
> Output: Result as dataframe

- The function : get_issues_from_projects() could also be a notebook by itself. Could you please create it ?
> Input: url + token
> Model: Function
> Output: Result as dataframe + verticalbar stacked bar with number of open/close issues
It will be cool to have the get_issues_from_repository as well :)

- Can you track the number of "open" issue and create a vertical barchart with :
BACKLOG : Number of issues
TO_DO : Number of issues
IN_PROGRESS : Number of issues
REVIEW : Number of issues
STALE_ISSUES : issues in to do, in progress, review with no activity for the last 7 days
STALE_PR : Pull request open with no activity for the last 7 days

Thanks a lot. You did an amazing job 🥇

**Comment by SanjuEpic** [comment]
Thanks for your review @FlorentLvr 
Will definitely work on these and then push to this PR.
Then we can merge this PR finally.

**Comment by SanjuEpic** [comment]
Hey @FlorentLvr!
Can I be creating a new notebook for each and every type of plot i.e total issues, open issues, closed issues, and open + stale issues or continue in a single notebook?

Let me know.

**Comment by SanjuEpic** [comment]
Hey @FlorentLvr, added new notebooks and changes, u can have a look.
If everything is good, then we can move onto integrating the code with Naas drivers.

Thanks!

**Comment by FlorentLvr** [comment]
@SanjuEpic , TY for your contribution. Everything is working well. I added your name as "author" in each notebook. 
I can not merged because of conflicts with the master branch. Could you please try to resolved it ? TY

**Comment by SanjuEpic** [comment]
Hi @FlorentLvr !
I guess now its resolved
Please try and let me know
Thanks!

**Pull request merged**
