### PR TITLE
Added: Match expressions

### LINKED ISSUE #1200: Python - Match pattern with regular expressions
example → https://www.airplane.dev/blog/12-useful-python-scripts-for-developers to be templated using [Naas template framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository) for production use.

### PR DESCRIPTION
**Pull request by srini047**
Closes #1200 

**Description:** It validates the entered email address and phone number using the [re](https://docs.python.org/3.9/library/re.html) and [phonenumbers](https://pypi.org/project/phonenumbers/) modules.

**Screenshots:**
image

[x] Followed the Template provided.

### CODE REVIEW

**Comment by srini047** [comment]
> @srini047 I see a typo on "Vaild email" vs "Valid email" → Can you fix ? ;)

Fixed the typo!!

**Comment by jravenel** [comment]
@srini047 just reveiwed my pull request, here are my comments already integrated in the template: 

- added tool name on title
- modified filename
- added input section
- added import lib section
- added a sentence to refer to the regex pattern building process
- added markdown to describe function
- reorder the check email and phone number and deleted the variable as input as they are asked in input form in output section

**Comment by jravenel** [comment]
Yes I asked for support from the team cause I don't know why the CI does not pass on formatting

**Comment by srini047** [comment]
> Yes I asked for support from the team cause I don't know why the CI does not pass on formatting

Oh okay👍🏼

**Comment by srini047** [comment]
> @srini047! Thank you for your contribution! 🙏. Just tried it and it's working well :)

Thanks a lot @FlorentLvr 
Looking forward to contribute more🚀

**Pull request merged**
