### PR TITLE
161 k nn find the stock with closest performance

### PR DESCRIPTION
**Pull request by abhinav3398**
yet to add documentation and markdown and also need to save the output to csv & png/jpg/jpeg.

### CODE REVIEW

**Comment by abhinav3398** [comment]
@Dr0p42 The notebook is ready for your review :) Let me know what you think of it.

**Comment by Dr0p42** [comment]
> @Dr0p42 The notebook is ready for your review :) Let me know what you think of it.

I will take a look tomorrow 💪

**Review by Dr0p42 — COMMENTED** [review]
Wow it's a very good submission @abhinav3398 👏 congrats. I will request reviews from contributors that have better knowledge of me with K-NN if you don't mind, but I feel that I was able to understand everything with all the information you provided :)

**Comment by Dr0p42** [comment]
Hello @MoomalQ, would you be ok to review this pull request please? I would like to have your input on this submission 🙏

**Comment by abhinav3398** [comment]
@FlorentLvr that should do it.

**Pull request merged**
