### PR TITLE
added create template link yaml file

### PR DESCRIPTION
**Pull request by SuhasBRao**
The **create_link_to_template.yaml** file creates a comment in PR with a link to the template (the .ipynb file that was either modified or added).

### CODE REVIEW

**Comment by FlorentLvr** [comment]
@Dr0p42, could please check this PR ? I think everything is good but I would prefer to merged as you mastered our CICD 🙏

**Comment by jravenel** [comment]
Hi @SuhasBRao we were thinking of re-activating this but @Dr0p42 wanted to know if you can provide proof of work via small video or anything so it can help him validate. Thanks a lot.

**Comment by SuhasBRao** [comment]
Hey @jravenel, Sure do I need to make a video of it working, i can do that on my forked repository and share it.

Is that what you meant by proof of work?

**Comment by jravenel** [comment]
> Hey @jravenel, Sure do I need to make a video of it working, i can do that on my forked repository and share it.
> 
> Is that what you meant by proof of work?

Yes exactly

**Comment by SuhasBRao** [comment]
Hey @jravenel, I have created a small demo kind of thing, I'm sharing a link for the same below. Please don't mind the background noise. 
You can find the video [here](https://drive.google.com/file/d/1-gBkUjVtAEjpXb4qHNAFlFwBTwBJiLvf/view?usp=share_link)

**Pull request merged**
