### PR TITLE
feat: GitHub - List branches

### PR DESCRIPTION
**Pull request by FlorentLvr**
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1954

### CODE REVIEW

**Comment by Benjifilly** [comment]
if you want me to add something or change something tell me @FlorentLvr

**Comment by Benjifilly** [comment]
Ready to review

**Comment by FlorentLvr** [comment]
> if you want me to add something or change something tell me @FlorentLvr 

Yes, actually I would like to create another notebook in the same branch that only list the active branches. Can you please try to do it?

**Comment by Benjifilly** [comment]
Is this what you asked for, I listed every branches with an open PR's @FlorentLvr

**Comment by Benjifilly** [comment]
Ready to review

**Pull request merged**
