### PR TITLE
feat: NASA Classification of Exoplanets

### PR DESCRIPTION
**Pull request by Mardiat-Iman**

### CODE REVIEW

**Comment by FlorentLvr** [comment]
@Mardiat-Iman, can you readapt your notebook as follow:
- Update title
- Update tags if needed
- Update author name and URL with your name and LinkedIn URL
- Write down a description in the fourth cell starting with "**Description:**"
- Add some references in the fifth cell starting with "**References:**" and then a list of website
- Respect IMO framework: Input / Model / Output
- In the Input section: add a cell called "Imports libraries" and another "Setup Variables"
- In the Model section: Split your code and add some markdown to explain it
- Add some comments within your code
- Make sure the notebook run entirely (restart kernel and run all cells)

**Comment by FlorentLvr** [comment]
@Mardiat-Iman, just checking! Do you need some help on this?

**Comment by Mardiat-Iman** [comment]
@FlorentLvr Yes, pls

**Comment by FlorentLvr** [comment]
> @FlorentLvr Yes, pls

Ok, what do you need exactly?
- Did you try to run your code in this notebook? Is it working?
- Did you start splitting your code?

**Comment by Mardiat-Iman** [comment]
I'm trying to split my code

**Comment by Mardiat-Iman** [comment]
@FlorentLvr  Wait, I'm figuring it out and getting the hang of it. If I get stuck I'll let you know.

**Comment by Mardiat-Iman** [comment]
@FlorentLvr What the notebook does is classify exoplanets in a given group of data, with the graph showing a graphical representation of exoplanets in the data set and the notebook giving an output of how many exoplanets are in the dataset.

**Comment by FlorentLvr** [comment]
@Mardiat-Iman, just checking, did you do the video explaining the notebook? Let me know if you have any issues.

**Comment by Mardiat-Iman** [comment]
@FlorentLvr Yes I did, how would you like me to send it to you.

**Comment by FlorentLvr** [comment]
@Mardiat-Iman, I don't have access to your notebook. It seems you deleted it from the branch. Could you please push it back?

**Pull request merged**
