### PR TITLE
1217-Create-Github-Repo

### LINKED ISSUE #1217: Python - Create GitHub repository
The objective is to create a template using [Naas IMO framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository-) inspired by the code on this link: https://github.com/hastagAB/Awesome-Python-Scripts/blob/master/Git_repo_creator/git_repo_creator.py

### PR DESCRIPTION
**Pull request by knshkp**
Closes #1217

### CODE REVIEW

**Comment by Dr0p42** [comment]
No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by jravenel** [comment]
@knshkp did you see the checks are not passing the CI? 
I cannot validate if checks do not pass but if you need help let me know what I can do

**Review by knshkp — COMMENTED** [review]
Actually am making some changes

**Review by knshkp — COMMENTED** [review]
I have making few changes check that out

**Comment by jravenel** [comment]
Screenshot 2022-10-04 at 22 56 04
still failing @knshkp should I take over?

**Comment by knshkp** [comment]
hey @jravenel thanks please checkout i think at this time all have passed

**Comment by jravenel** [comment]
@knshkp Thank you for submitting the PR. I made a few changes to the code and pushed it to the branch. Here is the list: 

- renamed file with the proper upper case for GitHub and specifying that it applies only to personal account
- rename title
- changed description
- renaming "Variable" to "Setup variables"
- added comment to indicate where to create personal access token
- gave spacing to variables

It's good to merge now.

**Comment by jravenel** [comment]
@knshkp merged, congrats!⚡️ Will make a post about it in a few minutes.

**Pull request merged**
