### PR TITLE
Yahoo Finance Code changes

### PR DESCRIPTION
**Pull request by megha2907**
Get USD/INR Rates and plot

### CODE REVIEW

**Comment by FlorentLvr** [comment]
@megha2907 , 
TY for your contribution. 
I just checked your notebook and rework the structure because it does not fit to our standard. The structure must be :
- Input
- Model
- Output
You can start from the "template.ipynb". It will be easier for you.
Your notebook is working well but I would like to know a bit more about your use case.
What is the markdown for ? Would you like to send an email with it ?

**Comment by megha2907** [comment]
@FlorentLvr 
I have made the requested changes and checkedin the latest file.

**Comment by FlorentLvr** [comment]
@megha2907 , TY for changes. It's working well.
I have done the following changes:
- the structure to make it more easy to understand => input = variables / model = action to prepare email / output = action to send email
- I also added the scheduler at the end of the notebook. I hope you don't mind.
- I changed the title for the graph but actually it's not sent in your email. Don't you think it could be great to have it in your email ?
Let me know if it's good for you and I will merge the PR. Thanks a lot

**Comment by megha2907** [comment]
> @megha2907 , TY for changes. It's working well. I have done the following changes:
> 
> * the structure to make it more easy to understand => input = variables / model = action to prepare email / output = action to send email
> * I also added the scheduler at the end of the notebook. I hope you don't mind.
> * I changed the title for the graph but actually it's not sent in your email. Don't you think it could be great to have it in your email ?
>   Let me know if it's good for you and I will merge the PR. Thanks a lot

Sure @FlorentLvr Sounds good. Thanks for the update.

**Comment by FlorentLvr** [comment]
Hi @megha2907 ! TY for your contribution 👍 🥇 !
Don't hesitate to spread the word :)

Naas_contrib_step1

**Pull request merged**
