### PR TITLE
Get GitHub profiles from teams

### PR DESCRIPTION
**Pull request by SanjuEpic**
The objective of this notebook is to get a data frame of all the members of a Github organization as an output.
The notebook has been created in the input, model, and output format.

referring to issue #214

### CODE REVIEW

**Review by FlorentLvr — APPROVED** [review]

**Comment by SanjuEpic** [comment]
What about this @FlorentLvr, can this be also merged?

**Comment by FlorentLvr** [comment]
@SanjuEpic, it's working well but now could you try to create a function for this notebook ? 
Then, you will be able to create a driver for it. To help, you can have a look at the get_commits function in the github driver.
TY :)

**Comment by SanjuEpic** [comment]
Sure thing @FlorentLvr

**Comment by SanjuEpic** [comment]
Hi @FlorentLvr, done my changes for get profiles from teams,
still one more left that is get starred members from repo.
So planning to complete for that tomorrow, for now lets close this PR once I update the new code and u review it
Thanks!

**Comment by FlorentLvr** [comment]
@SanjuEpic, well done ! It's working.
I just rework a bit the function and change the url in input. Let's work on the driver now :)

**Pull request merged**
