### PR TITLE
feat: add members to team from gsheet

### PR DESCRIPTION
**Pull request by SanjuEpic**
Hey @FlorentLvr!
Hope you are doing good,

Referring to this issue #959, here is the attached pull request

Thanks!

### CODE REVIEW

**Comment by FlorentLvr** [comment]
@SanjuEpic , could you please update your PR 🙏 (refer to comment below) ?
https://github.com/jupyter-naas/awesome-notebooks/pull/1000#issuecomment-1124733706

**Comment by FlorentLvr** [comment]
@SanjuEpic ! Hope you are doing well. Let me know if you have any issue on this one :)

**Comment by SanjuEpic** [comment]
Sure @FlorentLvr will definitely update this. No need to worry

**Comment by SanjuEpic** [comment]
Updated this PR @FlorentLvr!, will be going on with the others asap

Thanks!

**Comment by FlorentLvr** [comment]
@SanjuEpic ! TY for your contribution !

**Pull request merged**
