### PR TITLE
Langchain vector search PDF

### PR DESCRIPTION
**Pull request by srini047**
Fixes: #1893

### CODE REVIEW

**Comment by FlorentLvr** [comment]
@srini047, just checked your notebook and i got an error while reading the PDF. Could you please create an example that could work anytime using a PDF from an external link ? 🙏 
image

**Comment by srini047** [comment]
@FlorentLvr I have updated it. You can take a look and if you feel that there is lot of time in the `pip install` in the Naas lab, then let me update with `Open in colab` for better speed.

**Comment by FlorentLvr** [comment]
> @FlorentLvr I have updated it. You can take a look and if you feel that there is lot of time in the `pip install` in the Naas lab, then let me update with `Open in colab` for better speed.

Hey @srini047, I've reviewed your work and noticed that there isn't an example PDF link provided. Could you please include a working PDF URL for reference? You might consider adding a step to download it on Naas. Let me know if you have any questions 🙏

**Comment by jravenel** [comment]
@srini047 @FlorentLvr are we done with this one? We were talking about making a video with @srini047 this friday. Just want to make sure it's ready for prime time.

**Comment by srini047** [comment]
@FlorentLvr I have updated the PDF URL and also added the `Open in colab` button just in case it sometimes(initially) takes a lot of time to load in Naas.

@jravenel Sure I will be ready by then.

**Comment by jravenel** [comment]
So are we going to shoot the video on naas since you have the thing setup now?

**Comment by srini047** [comment]
> So are we going to shoot the video on naas since you have the thing setup now?

Yes all set from my end.

**Review by FlorentLvr — APPROVED** [review]

**Comment by FlorentLvr** [comment]
@srini047, i have added the weviate API key to make the notebook work and it's good now. Can you please try on your side?

I attempted to use the notebook with your PDF and another one from Tesla's results on the notebook itself, but the results didn't seem accurate. Could you provide an example where it worked well?

**Comment by srini047** [comment]
@FlorentLvr I get an error when I actually run it.
image

Can you give this [url](https://tesla-cdn.thron.com/static/SVCPTV_2022_Q4_Quarterly_Update_6UDS97.pdf?xseo=&response-content-disposition=inline%3Bfilename%3D%22b7871185-dd6a-4d79-9c3b-19b497227f2a.pdf) a try from your end by the time let's fix this error.

**Comment by srini047** [comment]
> @FlorentLvr I get an error when I actually run it. image
> 
> Can you give this [url](https://tesla-cdn.thron.com/static/SVCPTV_2022_Q4_Quarterly_Update_6UDS97.pdf?xseo=&response-content-disposition=inline%3Bfilename%3D%22b7871185-dd6a-4d79-9c3b-19b497227f2a.pdf) a try from your end by the time let's fix this error.

Also for me the kernel dies when I run the `Store the embeddings` cell. Is that the same case for you too?

**Pull request merged**
