### PR TITLE
WhatsApp-Heatmap

### PR DESCRIPTION
**Pull request by Mukhtarmid**
Tried my best! Any contribution is welcome.

### CODE REVIEW

**Comment by Dr0p42** [comment]
No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by Mukhtarmid** [comment]
#1813 fixed

**Comment by FlorentLvr** [comment]
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1340

**Comment by FlorentLvr** [comment]
@Mukhtarmid, thank you for your contribution. I made several changes to the notebook, including renaming it, updating the description and tags, implementing error handling for the installation of the library chatminer, and incorporating markdown formatting to improve clarity and readability.

**Review by FlorentLvr — APPROVED** [review]

**Comment by FlorentLvr** [comment]
> @Mukhtarmid, thank you for your contribution. I made several changes to the notebook, including renaming it, updating the description and tags, implementing error handling for the installation of the library chatminer, and incorporating markdown formatting to improve clarity and readability.

Please let me know if you are satisfied with these changes. If you are, you can merge this pull request; otherwise, I will take care of it by the end of the day.

**Comment by Mukhtarmid** [comment]
@FlorentLvr, First of all! I apologise for not following the template design. Secondly, I was in a bit tighten by time. Any which ways, thanks for helping hand.

**Pull request merged**
