### PR TITLE
feat: PyGWalker - Analyze Pandas dataframe

### PR DESCRIPTION
**Pull request by FlorentLvr**
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1540

### CODE REVIEW

**Review by aybruhm — COMMENTED** [review]
Hi @FlorentLvr, I am done with this task. Could you review it and assign more to me?

**Comment by FlorentLvr** [comment]
@aybruhm! Just add a try except to install pygwalker as it was not working on my naas. Could you please make a small gif to show how pygwalker works? I would like to use to promote this template :)

If you need some inspirations, here is a linkedin that demonstrates how it works: https://www.linkedin.com/posts/avi-chawla_python-datascience-pandas-activity-7036283018474364928-duoC?utm_source=share&utm_medium=member_desktop

Thank you :)

**Comment by FlorentLvr** [comment]
> Hi @FlorentLvr, I am done with this task. Could you review it and assign more to me?

Sure, what kind of templates would you like to work on?

**Comment by aybruhm** [comment]
> 

Of course, here you go:


https://user-images.githubusercontent.com/55067204/224766812-c4e1ed9c-c028-4988-aa4e-360f3ebf331e.mp4

**Comment by aybruhm** [comment]
> @aybruhm! Just add a try except to install pygwalker as it was not working on my naas. Could you please make a small gif to show how pygwalker works? I would like to use to promote this template :)
> 
> If you need some inspirations, here is a linkedin that demonstrates how it works: https://www.linkedin.com/posts/avi-chawla_python-datascience-pandas-activity-7036283018474364928-duoC?utm_source=share&utm_medium=member_desktop
> 
> Thank you :)

Thank you for doing that!

Of course, here you go:

https://user-images.githubusercontent.com/55067204/224768206-1ce52a7a-9b67-4d14-ba30-bcf73766f8f6.mp4

**Pull request merged**
