### PR TITLE
Google calendar - debug authorization

### PR DESCRIPTION
**Pull request by SanjuEpic**
Hey @FlorentLvr, @Dr0p42!
Hope you are doing good.

Referring to this issue #414 

I would like to ask you for some help with respect to the google calendar notebook setup, I have been getting some problem right after we allow all the permissions to the google calendar authorization.

I have provided detailed comments for setting up and proceeding with the notebook in an easy way.

Do let me know if you need any more information when you come across this issue

Thanks!

### CODE REVIEW

**Comment by Dr0p42** [comment]
Hello @SanjuEpic, not sure to get it, you still have an error?

Is this the "error" you are referring to? 
image

**Comment by SanjuEpic** [comment]
Yeah @Dr0p42, this is it, once we click the link I'm unable to get the authorization process completed.
Do let me know if you are able to compile that authorization step successfully.
Thanks

**Comment by Dr0p42** [comment]
OK @SanjuEpic, I will test to run this notebook end-to-end 👍 I keep you posted.

**Comment by SanjuEpic** [comment]
Yeah sure, even I have tried with service account, but still the output had the same error output.

Thanks for letting me know!

**Pull request closed without merging**
