### PR TITLE
notebook to convert audio from wav to mp3 added

### PR DESCRIPTION
**Pull request by Mohwit**
Please, have a look!

### CODE REVIEW

**Comment by Dr0p42** [comment]
No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by Mohwit** [comment]
@FlorentLvr I have corrected the author cell

**Comment by FlorentLvr** [comment]
@Mohwit, i made some changes on your code but i was not able to make it work.
Here below the error.
Do you confirm you have the same error?
image

**Comment by Mohwit** [comment]
@FlorentLvr Sure, working on it. Thanks

**Comment by Mohwit** [comment]
@FlorentLvr Can you please review now, there was some problem with the sample wav file I earlier used to test, I have updated the link and now it's working fine.

**Review by srini047 — APPROVED** [review]
LGTM 🚀

Works fine from my end @FlorentLvr @Mohwit

**Comment by Mohwit** [comment]
@FlorentLvr I still doesn't 100% sure what was the issue, but I looked at a lot place where people faced the similar issue and most were due to codec thing. Also, from_file() method solved most of the issues people people, which I also changed replacing 'from_wav()'. So, it should be working file for all now. Also, I tested it with multiple audio file, and it worked fine for all.

**Pull request merged**
