### PR TITLE
feat: Polars - Read dataframe

### PR DESCRIPTION
**Pull request by FlorentLvr**
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1542

### CODE REVIEW

**Review by srini047 — COMMENTED** [review]
I have made 2 basic changes:
- Added try-catch
- Also changed the alias from `p`to `pl`

But I get `AttributeError: 'DataFrame' object has no attribute 'read_csv'` when I run the notebook.


This will come to [rescue](https://pola-rs.github.io/polars-book/user-guide/quickstart/intro.html#quick-start).

**Comment by FlorentLvr** [comment]
@MinuraPunchihewa, hope you are doing well! Did you have time to have a look to this template?

**Comment by MinuraPunchihewa** [comment]
@FlorentLvr Apologies for the delay. Please allow me a couple more days, I will get this done.

**Comment by MinuraPunchihewa** [comment]
Hey @FlorentLvr,
I just had a look at this and I made a few small updates. I renamed it to `Polars_Read_CSV` because I thought that was more appropriate, but feel free to change it back.

**Review by srini047 — COMMENTED** [review]
Screenshot 2023-04-07 at 6 57 33 PM

Facing the same `AttributeError`. [Ref](https://github.com/jupyter-naas/awesome-notebooks/pull/1543#pullrequestreview-1339325296)

**Comment by FlorentLvr** [comment]
> Screenshot 2023-04-07 at 6 57 33 PM
> 
> Facing the same `AttributeError`. [Ref](https://github.com/jupyter-naas/awesome-notebooks/pull/1543#pullrequestreview-1339325296)

@srini047, it seems like the latest version was not pulled as the code mentioned earlier does not exist anymore.
@MinuraPunchihewa, I have updated the description of the notebook to provide more context about the "polars" library, including its functionality and possible use cases. 
LGTM now 🚀

**Pull request merged**
