### PR TITLE
PowerPoint Add Title + Line Presentation

### PR DESCRIPTION
**Pull request by ayoub-berdeddouch**

### CODE REVIEW

**Comment by ayoub-berdeddouch** [comment]
@FlorentLvr check it please!

**Comment by FlorentLvr** [comment]
> @FlorentLvr check it please!

@ayoub-berdeddouch! TY for your contribution.
Just checked you didn't add any line in your present. 
The objective is to create a title and insert a line below the title as follows:

image

**Comment by ayoub-berdeddouch** [comment]
> > @FlorentLvr check it please!
> 
> @ayoub-berdeddouch! TY for your contribution. Just checked you didn't add any line in your present. The objective is to create a title and insert a line below the title as follows:
> 
> image
> 
> Let me know if you have any doubt,
> 
> Florent

My bad @FlorentLvr!
I just fixed it, I was thinking it was a sub title as line haha 😸 
Well, check it now!
Best regards,

**Comment by jravenel** [comment]
@ayoub-berdeddouch good job! I validated the PR but I think we should focus on the way to set the position of the title and subtitle at the center of the page like any other ppt in the next iterations.

**Pull request merged**
