### PR TITLE
feat: Stable Diffusion - Generate image from text

### PR DESCRIPTION
**Pull request by jravenel**
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1750

### CODE REVIEW

**Comment by jravenel** [comment]
@FlorentLvr I'm adding you here as reviewer. @Rayryu don't hesitate to ask here if you need anything.

**Comment by Rayryu** [comment]
Thank you Jeremy for the introduction. And sorry for the late reply, I was
on sick leave.
Florent, I'll work on the issue this week. It should be done before your
next review (Thursday).

**Comment by Rayryu** [comment]
@FlorentLvr Well, I guess it's ready for review now.

**Review by srini047 — COMMENTED** [review]
Hey @Rayryu !!

I tried running the notebook in `app.naas.ai` but I am facing an issue while doing `pip install`.

Screenshot 2023-05-31 at 7 25 49 PM

Screenshot 2023-05-31 at 7 25 55 PM

I tried to reproduce the issue as per this issue: https://discuss.huggingface.co/t/datalore-importerror-cannot-import-name-flax-weights-name/34407 but still facing the same.

Also make sure to add: the `--user` flag in order to allow the installation of the packages in Naas platform.

**Comment by Rayryu** [comment]
@srini047 I will check this issue today. I'll let you know.

**Comment by Rayryu** [comment]
@srini047 Sorry for the late reply.
As expected, the issue is with the execution environment. In this case app.nass.ai kernels.
The error you shared above I believe is a result of the environment having old versions of the packages.

The solution is to update that package to the recent version using --update as argument.

Please note that the model loading part will probably crash the kernel if you're using the default configuration (4GB of RAM I believe). This was the reason why I wrote the notebook in a Colab instead. The second reason is that GPU must be enabled in the environment.

Let me know if that works for you.

**Comment by srini047** [comment]
> @srini047 Sorry for the late reply. As expected, the issue is with the execution environment. In this case app.nass.ai kernels. The error you shared above I believe is a result of the environment having old versions of the packages.
> 
> The solution is to update that package to the recent version using --update as argument.
> 
> Please note that the model loading part will probably crash the kernel if you're using the default configuration (4GB of RAM I believe). This was the reason why I wrote the notebook in a Colab instead. The second reason is that GPU must be enabled in the environment.
> 
> Let me know if that works for you.

Thanks for the update @Rayryu, will revert to you soon.

cc @FlorentLvr

**Comment by srini047** [comment]
@Rayryu I am getting an `Import error` in Colab as well.

https://colab.research.google.com/drive/1PYhRAo8bcgSJdIFrtAFUF2ENbe5BJhn7?usp=sharing

Screenshot 2023-06-06 at 9 23 49 AM

**Comment by Rayryu** [comment]
@srini047 You should restart the kernel after installing/updating the packages.

**Pull request merged**
