### PR TITLE
feat: Developing a model to create Correlation Heatmap

### LINKED ISSUE #2303: Matplotlib - Correlation Heatmap
## Description
A correlation heatmap is a graphical tool that displays the correlation between multiple variables as a color-coded matrix.
This notebook will demonstrate how to plot a correlation heatmap using Matplotlib. It is useful for data visualization.

### PR DESCRIPTION
**Pull request by rittikadeb**
## Fixes

This PR resolves #2303 

## What does this PR do?
Developed a model to create a Correlation Heatmap.

## Screenshots
image

### CODE REVIEW

**Review by srini047 — APPROVED** [review]
LGTM🚀

**Comment by rittikadeb** [comment]
Should I merge the pull request?

**Comment by FlorentLvr** [comment]
@rittikadeb, thank you for your contribution. I have started reviewing your template. While it is working, there are a few areas that need to be reworked to ensure the template is as simple as possible.

Here are the specific changes I would like you to make:

- Input Section: Currently, there is a cell called "Setup variables" in the input section. However, I expected to have the ability to set these variables in the cell below. Please update the template to allow for variable input in the appropriate cell.

- Model Section: There is no markdown in the model section to explain what the code is doing. Please add a clear explanation of the code's purpose to help users understand its functionality. Additionally, I would like users to be able to create the chart in this section. Please include the code for chart creation here.

- Output Section: I expect to see the graph and have the ability to create an HTML or PNG file that can be used outside of Naas. Please ensure that the graph is displayed in this section and provide the necessary code to export it as an HTML or PNG file.

Once you have made these changes, I will be happy to review and merge the template. 

You can refer to the "Matplotlib - Create barchart" template as an example. If you need further guidance, please consult the readme, which provides a comprehensive explanation of the framework. 

Feel free to reach out if you have any questions. Thank you! 🙏

image

**Review by FlorentLvr — CHANGES_REQUESTED** [review]
Here are the specific changes I would like you to make:

Input Section: Currently, there is a cell called "Setup variables" in the input section. However, I expected to have the ability to set these variables in the cell below. Please update the template to allow for variable input in the appropriate cell.

Model Section: There is no markdown in the model section to explain what the code is doing. Please add a clear explanation of the code's purpose to help users understand its functionality. Additionally, I would like users to be able to create the chart in this section. Please include the code for chart creation here.

Output Section: I expect to see the graph and have the ability to create an HTML or PNG file that can be used outside of Naas. Please ensure that the graph is displayed in this section and provide the necessary code to export it as an HTML or PNG file.

**Comment by rittikadeb** [comment]
Hey, I am having problem in pushing committed changes as I have forgotten my token!

**Comment by FlorentLvr** [comment]
> Hey, I am having problem in pushing committed changes as I have forgotten my token!

@rittikadeb 
You can remove the old one and generate a new! Don't forget to pull the branch to get the last changes 🙏

**Comment by rittikadeb** [comment]
Still I am having some issues. I will close this PR and open another one. Thanks!

**Pull request closed without merging**
