### PR TITLE
Added template Python_Organize_Directories_based_on_files_extensions

### LINKED ISSUE #1213: Python - Organize directory based on file types
The objective is to create a template using [Naas IMO framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository-) inspired by the code on this [LINK](https://github.com/hastagAB/Awesome-Python-Scripts/blob/master/Directory-organizer/Directory-oraganiser.py)

### PR DESCRIPTION
**Pull request by AhmedMousa-ag**
This PR closes #1213
- [ ]  #1213
I organized files based on data scientists' work as I assume that the user is mostly a data scientist. and I'm open to discussion.

### CODE REVIEW

**Comment by jravenel** [comment]
Thanks @AhmedMousa-ag, @FlorentLvr can you check please?

**Comment by FlorentLvr** [comment]
@AhmedMousa-ag! Nice work :) It's working perfectly 💯  TY for your contribution !

**Comment by jravenel** [comment]
> @AhmedMousa-ag! Nice work :) It's working perfectly 💯 TY for your contribution !

yeah :) @AhmedMousa-ag :)

**Comment by AhmedMousa-ag** [comment]
Thank you, always happy to help.

**Pull request merged**
