### PR TITLE
feat: Shutterstock - Search for images

### PR DESCRIPTION
**Pull request by FlorentLvr**
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1516

### CODE REVIEW

**Comment by FlorentLvr** [comment]
@srini047, just checking! Do you find a way to connect with the API ?

**Comment by srini047** [comment]
> @srini047, just checking! Do you find a way to connect with the API ?

@FlorentLvr I still couldn't figure out the correct callback URL. Due to which I feel we get this error:

```
{
  "message": "Invalid access token"
}
```

**Comment by FlorentLvr** [comment]
> > @srini047, just checking! Do you find a way to connect with the API ?
> 
> @FlorentLvr I still couldn't figure out the correct callback URL. Due to which I feel we get this error:
> 
> ```
> {
>   "message": "Invalid access token"
> }
> ```

Ok, don't hesitate to commit and push, if you are stuck.

**Comment by srini047** [comment]
> > > @srini047, just checking! Do you find a way to connect with the API ?
> > 
> > 
> > @FlorentLvr I still couldn't figure out the correct callback URL. Due to which I feel we get this error:
> > ```
> > {
> >   "message": "Invalid access token"
> > }
> > ```
> 
> Ok, don't hesitate to commit and push, if you are stuck.

@FlorentLvr Shared my notebook which I ran that lead to the error.

**Comment by FlorentLvr** [comment]
@Dr0p42, might need your help on this issue.

**Comment by FlorentLvr** [comment]
LGTM finally @srini047 🚀

**Pull request merged**
