### PR TITLE
Naas downloads chart

### PR DESCRIPTION
**Pull request by SanjuEpic**
Hey @jravenel !

As per our recent discussion, here is the PR for that.
Referring to issue #416 

Thanks!

### CODE REVIEW

**Comment by jravenel** [comment]
@SanjuEpic great work, it's working fine. Feedback : 
1) make it generic: 
→ we should have only one template in PyPi that could work for anyone willing to analyze their python library growth.
2) make these 2 about Naas accessible in Naas folder 
→ I would just move these 2 created there, and add a new one called "Total Downloads Naas librairies" 

What do you think? :)

**Comment by SanjuEpic** [comment]
Hey @jravenel thank you for the feedback,
Yes thought of making it that way.
But still, the notebook template is generic we just need to replace the name of the "package" variable for different functionalities.

And coming to 2nd point will move these 2 notebooks into naas folder and also create a new notebook "Total downloads naas libraries"

Thanks

**Comment by SanjuEpic** [comment]
All changes done, do have a look and then merge the PR @jravenel 
Thanks!

**Comment by FlorentLvr** [comment]
@SanjuEpic, TY for you contribution it's a great work ! :)

**Pull request merged**
