### PR TITLE
feat: Gmail - Create draft email

### PR DESCRIPTION
**Pull request by FlorentLvr**
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1766

### CODE REVIEW

**Comment by FlorentLvr** [comment]
@srini047, you can work on this issue as well!

**Comment by FlorentLvr** [comment]
@srini047, TY for your contribution! 
I reworked your notebook to put all variables on top and add some description! Can you try it again to ensure it also works on your side? Thank you 🙏

**Comment by srini047** [comment]
@FlorentLvr Done a minor change to keep the input as `string` rather than `list`. Now everything works as expected.

**Comment by FlorentLvr** [comment]
> @FlorentLvr Done a minor change to keep the input as `string` rather than `list`. Now everything works as expected.

Great! Just update the definition of the variable regarding to your changes! Thank you for your contribution 🙏

**Pull request merged**
