### PR TITLE
feat: LangChain - JSON Agent

### PR DESCRIPTION
**Pull request by FlorentLvr**
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1839

### CODE REVIEW

**Comment by srini047** [comment]
@FlorentLvr Do have a look at the PR.

**Comment by FlorentLvr** [comment]
> @FlorentLvr Do have a look at the PR.
> 
>  Screen.Recording.2023-07-03.at.11.59.42.AM.mov

Hi @srini047! I checked your video and saw that you uploaded a 'test.json' file to make the Naas notebook work. Do you know any examples of directly calling a JSON file from a URL?

The same as I did for LangChain - CSV Agent:
image

Thank you 🙏

**Comment by srini047** [comment]
> > @FlorentLvr Do have a look at the PR.
> > 
> >  Screen.Recording.2023-07-03.at.11.59.42.AM.mov
> 
> Hi @srini047! I checked your video and saw that you uploaded a 'test.json' file to make the Naas notebook work. Do you know any examples of directly calling a JSON file from a URL?
> 
> The same as I did for [LangChain - CSV Agent](https://github.com/jupyter-naas/awesome-notebooks/blob/master/LangChain/LangChain_CSV_Agent.ipynb):
> image
> 
> Can you also update the variables in "Setup Variables" to be the same as I did?
> 
> Thank you 🙏 

Sure, it's possible let me update it

**Comment by srini047** [comment]
> > > @FlorentLvr Do have a look at the PR.
> > > Screen.Recording.2023-07-03.at.11.59.42.AM.mov
> > 
> > 
> > Hi @srini047! I checked your video and saw that you uploaded a 'test.json' file to make the Naas notebook work. Do you know any examples of directly calling a JSON file from a URL?
> > The same as I did for [LangChain - CSV Agent](https://github.com/jupyter-naas/awesome-notebooks/blob/master/LangChain/LangChain_CSV_Agent.ipynb):
> > image
> > Can you also update the variables in "Setup Variables" to be the same as I did?
> > Thank you 🙏
> 
> Sure, it's possible let me update it

Done @FlorentLvr !

**Comment by FlorentLvr** [comment]
> > > > @FlorentLvr Do have a look at the PR.
> > > > Screen.Recording.2023-07-03.at.11.59.42.AM.mov
> > > 
> > > 
> > > Hi @srini047! I checked your video and saw that you uploaded a 'test.json' file to make the Naas notebook work. Do you know any examples of directly calling a JSON file from a URL?
> > > The same as I did for [LangChain - CSV Agent](https://github.com/jupyter-naas/awesome-notebooks/blob/master/LangChain/LangChain_CSV_Agent.ipynb):
> > > image
> > > Can you also update the variables in "Setup Variables" to be the same as I did?
> > > Thank you 🙏
> > 
> > 
> > Sure, it's possible let me update it
> 
> Done @FlorentLvr !

@srini047,
Can you manage the JSON file only inside the variable "json_path"? And try the JSON Agent with this URL: "http://api.worldbank.org/v2/countries/USA/indicators/SP.POP.TOTL?per_page=5000&format=json", I found it on https://github.com/jdorfman/awesome-json-datasets#climate
image

Then, in the cell below, can you create a function to manage both formats (JSON or URL) inside the same variable "json_path"? (If json_path.startswith("http") and json_path.endswith(".json"))
image

Also, you didn't add the variable "api_key" and "temperature" on top of the notebook, can you add it and update the variable description? Thank you 🙏

**Comment by srini047** [comment]
> LangChain - CSV Agent

- I tried using the JSON file from the URL and run the notebook. But it is failing to validate in the JSONSpec function, not quite sure of why this is happening.
- Also checked the JSON from the URL on an online JSON validator tool and verified it to be a valid JSON.

Any help on this is appreciated. Else we are good to go without this.

image

**Comment by FlorentLvr** [comment]
> > LangChain - CSV Agent
> 
> * I tried using the JSON file from the URL and run the notebook. But it is failing to validate in the JSONSpec function, not quite sure of why this is happening.
> * Also checked the JSON from the URL on an online JSON validator tool and verified it to be a valid JSON.
> 
> Any help on this is appreciated. Else we are good to go without this.
> 
> image

@srini047, After conducting several tests, I discovered that it was more effective to use a JSON file created within the notebook for this specific template. Moving forward, we should explore larger JSON files, as I have also noticed that LangChain struggles to handle datasets of considerable size, such as our templates.json.

**Comment by srini047** [comment]
> > > LangChain - CSV Agent
> > 
> > 
> > 
> > * I tried using the JSON file from the URL and run the notebook. But it is failing to validate in the JSONSpec function, not quite sure of why this is happening.
> > * Also checked the JSON from the URL on an online JSON validator tool and verified it to be a valid JSON.
> > 
> > Any help on this is appreciated. Else we are good to go without this.
> > image
> 
> @srini047, After conducting several tests, I discovered that it was more effective to use a JSON file created within the notebook for this specific template. Moving forward, we should explore larger JSON files, as I have also noticed that LangChain struggles to handle datasets of considerable size, such as our templates.json.

Thanks for providing insights on the same!

**Pull request merged**
