### PR TITLE
feat: Pydub - Convert audio file M4A to MP3

### PR DESCRIPTION
**Pull request by jravenel**
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1681

### CODE REVIEW

**Comment by FlorentLvr** [comment]
@jravenel, just checking! Did you work on this issue? Need any help?

**Comment by Benjifilly** [comment]
@FlorentLvr FlorentLvr this one is a bit complicated and I don't know how to do it because the library requires ffmpeg to work, but in this case we're on a notebook and I don't know how to manage it.

**Comment by FlorentLvr** [comment]
> @FlorentLvr FlorentLvr this one is a bit complicated and I don't know how to do it because the library requires ffmpeg to work, but in this case we're on a notebook and I don't know how to manage it.

@Benjifilly, no pb. I will have a look on this one. Thank you for your feedback! 🙏

**Comment by Benjifilly** [comment]
👍

**Pull request merged**
