### PR TITLE
1976 gmail list most interesting emails

### PR DESCRIPTION
**Pull request by tony-georgiev**

### CODE REVIEW

**Comment by FlorentLvr** [comment]
@tony-georgiev, just checking, do you need some help on this? Can you push your latest changes?

**Comment by FlorentLvr** [comment]
@tony-georgiev, the issue on the naas_drivers 'email' is fixed. You can now use Get_emails_by_dates
You can restart your engine to access the latest version by clicking on "File" / "Hub Control Panel" > "Stop my server" (wait) > "Start my server".


image

**Comment by tony-georgiev** [comment]
@FlorentLvr 
Ready to review

**Comment by tony-georgiev** [comment]
@FlorentLvr 
Ready to review

**Comment by FlorentLvr** [comment]
@tony-georgiev! Great work :). I am going to use it on my own :)

**Pull request merged**
