### PR TITLE
Resolves #1880

### LINKED ISSUE #1880: Advertools - Crawl a website
**Describe the problem you are facing**
Start with a URL (typically the home page), and get all pages of a website converted to a `DataFrame`.

**Describe the solution you'd like**
One line of code that does the conversion. Optionally add many different combinations of crawling options.

- Input
  - One or more start URLs
  - Various other options for which links to follow, which page elements to extract, crawling behavior, etc.
- Model 
Run the advertools `crawl` function
- Output
Crawl df: Each URL is represented with a row, and each column includes details about an element of the page (title, h1, meta description, etc)

**Additional context**
[advertools crawl function](https://advertools.readthedocs.io/en/master/advertools.spider.html)

### PR DESCRIPTION
**Pull request by eliasdabbas**
Resolves #1880

### CODE REVIEW

**Comment by Dr0p42** [comment]
No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by FlorentLvr** [comment]
@srini047, do you might have a look on this issue please? 🙏

**Comment by eliasdabbas** [comment]
@srini047 I'm not sure I see the code. Did you share the code? The actual code, not a description of it. 
If you ran with "naas.ai" it will not work because this is not a URL. This is a domain name. 
This is a URL: `https://www.naas.ai/` for example.

**Comment by FlorentLvr** [comment]
@eliasdabbas! Just added the install and made some minors change but it's working perfectly! Thank you for your contribution 🙏

**Pull request merged**
