### PR TITLE
Added: twilio-make-call

### PR DESCRIPTION
**Pull request by srini047**
Closes: #1224 

Worked on Twilio calling functionality.

### CODE REVIEW

**Comment by Dr0p42** [comment]
No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by FlorentLvr** [comment]
Hi @srini047!
TY for your contribution 👍 
As I don't have a Twilio account, I am not able to test your notebook.
Could you please add more documentation to help me test it out:
- A notebook description below the cell "Author"
- A process to get variables needed to setup a Twilio account
- A quick video to show how it works (optional but would be super helpful 🙏) 
Let me know if I can help you :)

**Comment by jravenel** [comment]
@srini047 +1 on @FlorentLvr comment

**Comment by srini047** [comment]
Sure. Will do the needful😊

**Comment by jravenel** [comment]
I suggest you use the Loom extension with GitHub for the video : https://www.loom.com/blog/loom-github-chrome-extension-integration

**Comment by srini047** [comment]
Haven't tried it yet but a thing to attempt.

**Comment by srini047** [comment]
## Notebook Output
image

## Call Recording
https://user-images.githubusercontent.com/81156510/195889361-0113fc8e-8597-46e4-bf21-5cb4fded4f31.mp4

## Call Output
https://user-images.githubusercontent.com/81156510/195887979-b002ccec-953f-4c08-b621-227fae5c256a.mp4

**Comment by FlorentLvr** [comment]
> ## Notebook Cell Output
> image
> 
> ## Call Recording
>  record-1665762613102.mp4 
> ## Call Output
>  video_2022-10-14_21-17-29.mp4

@srini047, 
-> what is the purpose of the "url" parameter?
-> can you add a description and a tutorial video if possible? 🙏 
Let me know if you have any questions!

**Comment by srini047** [comment]
> > ## Notebook Cell Output
> > image
> > ## Call Recording
> > record-1665762613102.mp4
> > ## Call Output
> > video_2022-10-14_21-17-29.mp4
> 
> @srini047, -> what is the purpose of the "url" parameter? -> can you add a description and a tutorial video if possible? 🙏 Let me know if you have any questions!

- The URL parameter is required to avoid this error: `TwilioRestException: HTTP 400 error: Unable to create record: Url parameter is required.` More details about the same are available [here](https://www.twilio.com/docs/voice/tutorials/how-to-make-outbound-phone-calls/python#:~:text=API%20Reference.-,Make%20an%20outbound%20call%20with%20hosted%20TwiML,-This%20uses%20the)
- Let me add a description

**Comment by FlorentLvr** [comment]
@srini047! TY for your contribution :). It's definitely clearer with the description 🙏

**Pull request merged**
