### PR TITLE
2255 matplotlib create piechart

### PR DESCRIPTION
**Pull request by MSaiKiran9**
## Fixes

closes : #2255 

## What does this PR do?
It shows how to use matplotlib piecharts 

## Screenshots
image

### CODE REVIEW

**Comment by Dr0p42** [comment]
No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by FlorentLvr** [comment]
@MSaiKiran9, TY for your contribution. Here are my feedbacks:
- You didn't add your LinkedIn URL in the author cell, could you please add it?
- I added cell at the end to be able to export the chat and create an asset that could be used outside naas but your code is code created a fig object. Could you please update it following the same example as https://matplotlib.org/stable/plot_types/stats/pie.html#sphx-glr-plot-types-stats-pie-py ? If you have any trouble you can get inspired by the other template like "Matplotlib_Create_Barchart.ipynb"/
Don't forget to pull before doing new changes. 
Let me know if you have any questions,

**Comment by MSaiKiran9** [comment]
Hi @FlorentLvr can you see if it's okay now ?

**Comment by FlorentLvr** [comment]
> Hi @FlorentLvr can you see if it's okay now ?

@MSaiKiran9, I made a little adjustements but it's good now! For next contribution, please make all variables have a description in the output section and add markdown cell to explain all steps (one was blank in output). TY 🙏

**Pull request merged**
