### PR TITLE
Telegram

### PR DESCRIPTION
**Pull request by yaswanthkumargothi**
A Telegram bot to get crypto sentiment.

### CODE REVIEW

**Comment by FlorentLvr** [comment]
Hi @yaswanthkumargothi,

Thank you for your contribution. 
We just reviewed your work and made the change below.
We didn't manage to run the script entirely. 
Could you please send us a video with the end-to-end workflow ?


List of changes made :
- Add pip install telegram before import library
- Move "import library" to "Input" section
- Remove ".ext" in "from telegram.ext import *" to make it work
- Add heading 3 "Variables" before credentials TELEGRAM_API_KEY and NEWSAPI_API_KEY
- Move "setup login" to "Input" section, could you please explain us what is it for a single sentence ?
- Could you please explain more the first function in the "Model" section
- Could you please remove "if __name__ == '__main__':" in "Output" section

Let us know if you have any question or join us in the next community call.
Thank you :)

**Comment by yaswanthkumargothi** [comment]
Hi @FlorentLvr,

I have added the proposed changes. 

1. The `telegram.ext` submodule is built on top of the pure API implementation. [Its an advanced API in the same package](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-Your-first-Bot). 
2. Logging is used to track events. There are so many events happening in a bot. 
`logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO)
logging.info('Starting Bot...')`

> In the first line, we are giving the format and the level of the logging information to be printed to STDOUT. DEBUG is the finest, INFO is brief that the event happened. The second line is for a confirmation that the bot started.

3. I commented in the notebook the detailed functioning of each line of "Model" section

**Comment by yaswanthkumargothi** [comment]
Hello @FlorentLvr,

Check this video for detailed workflow,

https://www.loom.com/share/b9c560575eac4935a51964249d7984ec

**Comment by jravenel** [comment]
Let's meet on Friday to validate this @yaswanthkumargothi

**Comment by jravenel** [comment]
@yaswanthkumargothi as discussed, please just add your name surname email in the author section ;) Good job 👍

**Comment by yaswanthkumargothi** [comment]
@jravenel, I didn't see the recent commits made by you in the notebook. The last push is the first version I committed. Could you please push the latest commit. So that, I can update changes to the author section.

**Comment by jravenel** [comment]
@FlorentLvr @Dr0p42 is it possible to fix the conflicts other than manually? There is 21 to do...

**Comment by jravenel** [comment]
It's merged 😉 @yaswanthkumargothi

**Pull request merged**
