### PR TITLE
1235 generate contribution certificate when pr is merged

### PR DESCRIPTION
**Pull request by SuhasBRao**
Creating a PR to generate a contribution certificate. A contribution certificate is generated when a PR is merged with the master branch.

### CODE REVIEW

**Comment by SuhasBRao** [comment]
If everything works well, a certificate should be generated after this PR is merged to master branch.

**Comment by SuhasBRao** [comment]
Hi @jravenel and @Dr0p42 , can you review the changes in this PR

**Comment by jravenel** [comment]
Hey @SuhasBRao just a doubt. Where is the certificate generated? Is it pushed as a comment in the issue? in the PR?

**Comment by SuhasBRao** [comment]
Python script generates the certificate in ** .github/Contributor_certificates/ **
This is then shown in the comments section of the PR

**Comment by SuhasBRao** [comment]
After python script generates the certificate it is pushed as a commit using .yaml

**Comment by jravenel** [comment]
as a commit where? Not clear to meet where the actual file is generated

**Comment by SuhasBRao** [comment]
Inside .gitHub folder a new folder will be created with the name Contributor_certificates inside which will be the certificates

**Comment by jravenel** [comment]
> Inside .gitHub folder a new folder will be created with the name Contributor_certificates inside which will be the certificates

Oh, ok, I'm sorry, this is badly scoped maybe by me, I was hoping to see this as a comment in the Issue or the PR associated. .. is it possible?

Otherwise we will just overload the repo with certificates, that will grow the size of the repo and we try to keep it as small as possible.

**Comment by SuhasBRao** [comment]
Oh, sorry my bad, I thought of creating a separate folder for it. Yes you are right this will overload the repo. 
I will try to create a certificate just as a PR comment. I think we can do it.👍

**Comment by SuhasBRao** [comment]
Will it be fine if I just host the image elsewhere and link it as image. I'll explore more about this.

**Comment by Dr0p42** [comment]
>  Will it be fine if I just host the image elsewhere and link it as image. I'll explore more about this.

Hello @SuhasBRao, I don't know if it's possible to use the assets upload mechanism of Github, that would be awesome.

Worst case scenario then we may need to provide an s3 location for this.

**Comment by SuhasBRao** [comment]
I actually tried using GitHub artifacts but I wasn't able to get  links for those artifacts. Is there any way we can get links for those.

**Comment by jravenel** [comment]
@SuhasBRao @Dr0p42 it it's too complicated, and if we have the email of the contributors (we should), is it more simple to send email to the contributor?

**Comment by SuhasBRao** [comment]
@Dr0p42 Yeah, I'll share it just a minute

**Comment by SuhasBRao** [comment]
@Dr0p42 , This is an old version I was trying with, [here](https://github.com/SuhasBRao/awesome-notebooks/blob/03f4a079c46badc9f5700307612b5f91d996ebcc/.github/workflows/generate_certificate_on_merge.yaml). Its kind of messy. Ignore those comments.

**Comment by SuhasBRao** [comment]
@jravenel and @Dr0p42, I found this article [here](https://dev.to/shcheklein/learning-github-actions-creating-beautiful-pr-comments-ibk) using which we can create to the commit  like shown below,

Screenshot from 2022-10-18 11-47-57

Let me know what you think?

**Comment by SuhasBRao** [comment]
Guys @jravenel and @Dr0p42, I found a free image hosting website called [imgbb](https://api.imgbb.com/). Using this I modified generate_certificate.yaml a bit, now we can put the certificate in PR without the need to store it on github. Here's the snapshot of the same, 

Screenshot from 2022-10-19 12-15-32

Here's the workflow run,

Screenshot from 2022-10-19 12-15-56

We just need to sign up for imgbb to get a free token, and store it as a github secret that will be accessed by .yaml. No need to  overload the repository with certificates,

Let me know what you think ?

**Comment by SuhasBRao** [comment]
@jravenel and @Dr0p42, can you review these changes? And let me know what you think about the certificate being hosted on imgbb.

**Comment by jravenel** [comment]
I think we should reopen this and add some suggestion of posts to be shared on social media using generative AI @SuhasBRao @FlorentLvr

**Comment by jravenel** [comment]
To close this PR, we discussed today about: 

1/ Get all the files added and create a certificate for each file
Let's cover all the edge cases. 

2/ make a suggestion of post on Twitter and LinkedIn using OpenAI 
@FlorentLvr can suggest a prompts?
→ maybe in another issue this one

**Comment by SuhasBRao** [comment]
Hey @FlorentLvr do i have to make it generate certificate for all the files modified in a PR, if that's the case won't this be too much lets say a person modifies 5 .ipynb files then, we would have to generate 5 certificates. 

Also right now we are saving the cerficates in [imgbb](https://imgbb.com/), a free image hosting platform. Shall i continue with the same.

**Comment by FlorentLvr** [comment]
> PR

Hi @SuhasBRao! You are right. It might be too much. Do you think you can add all files changed in one certificate?
About the certificate in imgbb, to your opinion, are there any red flags using this?

**Comment by FlorentLvr** [comment]
> > PR
> 
> Hi @SuhasBRao! You are right. It might be too much. Do you think you can add all files changed in one certificate? About the certificate in imgbb, to your opinion, are there any red flags using this?

Hi @SuhasBRao, just checking? Let me know if it is possible to do :)

**Comment by SuhasBRao** [comment]
> > > PR
> > 
> > 
> > Hi @SuhasBRao! You are right. It might be too much. Do you think you can add all files changed in one certificate? About the certificate in imgbb, to your opinion, are there any red flags using this?
> 
> Hi @SuhasBRao, just checking? Let me know if it is possible to do :)

Hey @FlorentLvr, yes its possible to add the files, I'm not able to figure out the part to make a suggestion to post it in linkedin or twitter using OpenAI

**Comment by SuhasBRao** [comment]
@FlorentLvr , @jravenel let me know what you think of the certificate, it also contains details about the files modified, this checks for all the files. Do i have to change it to detect only the .ipynb files
The certificate contains certain values for testing purposes.

image

**Comment by FlorentLvr** [comment]
> > > > PR
> > > 
> > > 
> > > Hi @SuhasBRao! You are right. It might be too much. Do you think you can add all files changed in one certificate? About the certificate in imgbb, to your opinion, are there any red flags using this?
> > 
> > 
> > Hi @SuhasBRao, just checking? Let me know if it is possible to do :)
> 
> Hey @FlorentLvr, yes its possible to add the files, I'm not able to figure out the part to make a suggestion to post it in linkedin or twitter using OpenAI

@SuhasBRao, great work! About the linkedin or twitter workflow, we will work it out in another issue :)

**Comment by FlorentLvr** [comment]
> @FlorentLvr , @jravenel let me know what you think of the certificate, it also contains details about the files modified, this checks for all the files. Do i have to change it to detect only the .ipynb files The certificate contains certain values for testing purposes.
> 
> image

@jravenel, sounds good to me! What do you think?

**Review by FlorentLvr — APPROVED** [review]

**Comment by jravenel** [comment]
I want my first certificate 😉

**Comment by SuhasBRao** [comment]
Let all of us get a certificate and post it in social media 😊

**Comment by SuhasBRao** [comment]
@FlorentLvr, we need to add a secret for the the action to work, also i'm making few more changes will create a new PR soon.

**Pull request merged**
