### PR TITLE
feat: lefigaro analyze house price

### PR DESCRIPTION
**Pull request by jravenel**
adding the notebook we have been reviewing with @Mahanamana 
@Mahanamana please sign off the notebook by adding your name and social media link to the Author cell and submit new PR. 
@FlorentLvr will review after that done.

### CODE REVIEW

**Comment by jravenel** [comment]
It seems it's also missing the tool #lefigaro to be added in the Tools cell. 
Screenshot 2022-06-11 at 08 50 25

**Comment by Mahanamana** [comment]
@jravenel the notebook is already updated (cell author)

**Comment by jravenel** [comment]
> @jravenel the notebook is already updated (cell author)

you mean you added it right? It was not updated before.

**Comment by Mahanamana** [comment]
@jravenel Yes that's it

**Comment by Mahanamana** [comment]
I already updated them

**Comment by FlorentLvr** [comment]
@Mahanamana , just fix the issue about the author. Is it ok to merged this PR @jravenel?

**Comment by FlorentLvr** [comment]
@Mahanamana ! TY for your contribution :). Just checked it and it's working well 💯 👍

**Pull request merged**
