### PR TITLE
Cryptocurrency Heatmap and Correlation graph

### PR DESCRIPTION
**Pull request by carloocchiena**
Get live data from the web and compute data viz and analysis about different cryptocurrencies

### CODE REVIEW

**Review by carloocchiena — COMMENTED** [review]
seen; as expected.

**Comment by FlorentLvr** [comment]
Hi @carloocchiena ! TY for your contribution. 
I splitted your notebook in 2 bc you made 2 templates in one :
- Create candlestick from ticker
- Create heatmap and correlation graph.
I also rework the structure of your notebook and divide your code to fit to our standard : input, model, output.
Can you check and let me know if it's good on your side again !
TY :)

**Comment by carloocchiena** [comment]
Hi @FlorentLvr! 
Fine, thank you! I checked both and I can confirm they are fine on my side,
but is not totally clear to me why there are 8 files in review in this PR, I was expecting two (the split of the single original file).
Am I missing something?
I flagged as reviewed the two i checked, for the time being.

**Comment by FlorentLvr** [comment]
> Hi @FlorentLvr! Fine, thank you! I checked both and I can confirm they are fine on my side, but is not totally clear to me why there are 8 files in review in this PR, I was expecting two (the split of the single original file). Am I missing something? I flagged as reviewed the two i checked, for the time being.

@carloocchiena ! Cool. Sorry for the 8 files. I made some changes on your branch to add the author to the other notebooks. I merge your PR then.
TY for your contribution ! 💯

**Pull request merged**
