### PR TITLE
[Issue #1094] Oura Ring Awesome Notebook

### LINKED ISSUE #1094: Oura - Send text when hours of sleep are low
**Describe the problem you are facing**
When I don't have enough hours of sleep, my mental health decline. 

**Describe the solution you'd like**
I want automation to send a text to my support network to ask if I'm ok. 

- **Input**: 
    - API KEY
    - Contact phone: +33695256922
    - Contact name: Jeremy 
    - Threshold hours of sleep: 5
- **Model** 
    - Get sleep periods 
    - Calculate moving sleep average 
    - If below X hours text someone 
- **Output** 
    - Create chart
    - Send text message alert 

**Additional context**
API resources: https://cloud.ouraring.com/docs/daily-summaries

### PR DESCRIPTION
**Pull request by onthemarkdata**
This PR resolves #1094.

Got sleep data running end to end:
Screen Shot 2022-09-02 at 8 11 48 PM

### CODE REVIEW

**Comment by Dr0p42** [comment]
No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by jravenel** [comment]
Hey @mellamomark, I move your issue to review but as we have no Oura ring, do you mind doing a short video to demo and explain the code using loom or something like this?

**Comment by jravenel** [comment]
Hey @onthemarkdata, Sorry for staling this issue, I was hoping to do a video with you before but let's validate this. 
Can we sync for recording where I will basically interview you and you show me how it works?

**Comment by jravenel** [comment]
Hey @onthemarkdata, just to let you know I just sent a reques to partner with Oura team and create a data product to use Oura data.

**Comment by jravenel** [comment]
closing this as we did not find a way to test.

**Pull request closed without merging**
