### PR TITLE
Twitter from URL using snscrape

### PR DESCRIPTION
**Pull request by tdubon**
Creates dataframe with following fields :
URL
TITLE
CONTENT
HASTAGS
DATE
LIKES
RETWEETS

Output:
2 graphs and a file

### CODE REVIEW

**Comment by jravenel** [comment]
Hello @tdubon, 

Thanks for your contribution. 
Here below my feedback; 

1/ Your file "Get_tweets_from_URL.ipynb " was on the root of awesome-notebooks
→ It should have been in the "Twitter" folder with the name "Twitter_Get_tweets_from_URL.ipynb"

2/ When I look at the structure of the notebook, the "Model" part of the framework is missing. 
→ To follow the framework you should have an "Input" section with all the variables, "Model" section with the function, "Output" section for the result. 

3/ I did not manage to see the final dataframe expected, but it seems you made a viz.
→ The notebook should be simplified to get only the dataframe expected in output as a first step. 
let's keep this simple :)

== I proposed some changes so you can see how we need to do for the next contributions
Does that makes sense to you? 

Here you can see the structure of the notebook
Screenshot 2021-12-27 at 13 03 31

Here the display of the json in the model section
Screenshot 2021-12-27 at 13 03 49

Here clean and transform to get the expected output specified in the Issue.
Screenshot 2021-12-27 at 13 03 57


FYI @FlorentLvr @Dr0p42

**Comment by jravenel** [comment]
@tdubon I let you check this on your side, it's your turn to give me feedback 😇 then we can merge.
I propose that next contribution, we create a new notebook that send the output to Notion. "Twitter+Notion_Send_tweet_stats_to_database"

It's an actual need we have to follow social content for Naas. Are you interested?

**Review by tdubon — COMMENTED** [review]
Jeremy, thanks for the helpful feedback. It's clear how to format the file moving forward. To verify, you've made the updates already and I don't need to reflect them in the file on the Naas server?

**Comment by jravenel** [comment]
> 1@jravenel, thanks for the helpful feedback. It's clear how to format the file moving forward. Also, will make sure to simplify naming and stick to the requirements. To verify, you've made the updates already and I don't need to reflect them in the file on the Naas server? Let me know if I do!
> 
> Yes, I can work on the suggested contribution next.

What do you mean by "reflect them in the file on the Naas server?" If you pull from your branch you will see my changes yes. Nothing more to do.

I'll merge then.

**Pull request merged**
