### PR TITLE
2257 google sheets create new sheet

### LINKED ISSUE #2257: Google Sheets - Create new sheet
This notebook will show how to create a new sheet in Google Sheets using Python. It is usefull for organizations that need to create new sheets in Google Sheets.

### PR DESCRIPTION
**Pull request by MSaiKiran9**
## Fixes

This PR resolves #2257 

## What does this PR do?
(Provide a description of what this PR does and why it's needed.)
It'll create a new google sheet and can share with people.

### CODE REVIEW

**Comment by MSaiKiran9** [comment]
Hi @FlorentLvr can you see if it's good to go ?

**Review by srini047 — APPROVED** [review]
LGTM🚀
@FlorentLvr

**Comment by FlorentLvr** [comment]
@MSaiKiran9, I was not able to follow your procedure. I did not really understand what I had to do so to guid you I create a another notebook that creates a new spreadsheet from a spreadsheet name. Can you have a look and try to adapt your notebook to the one I did to make sure I can test yours? 
Thanks you!

The notebook is: Google_Sheets_Create_new_sheet_from_spreadsheet_name.ipynb

**Comment by MSaiKiran9** [comment]
Hi @FlorentLvr , thankyou for your review . As you can see from this image 
image
I was able to produce a sheet , share the sheet with a person's mail and it's link using the above sheet , but if you think it's not readable I can edit the sheet further .

**Comment by FlorentLvr** [comment]
> Hi @FlorentLvr , thankyou for your review . As you can see from this image image . I used the naas secret to store the credentials object . I was able to produce a sheet , share the sheet with a person's mail and it's link using the above sheet , but if you think it's not readable I can edit the sheet further .

@MSaiKiran9, great but yes, it's not really easy to read it and understand the steps. Here is what I propose to improve:
- Try to put all variables that the user needs to update. For example, the "SCOPES" is not a variable that we want the user to set but the api_key or spreadsheet ID are. 
- The model section should be about creating the new sheet.
- The output section should be about displaying and accessing the result
If you pull the branch you will access my notebook that might guid you to improve yours. 
Let me know if you have any others questions! 🙏

**Comment by MSaiKiran9** [comment]
@FlorentLvr Sure I'm on it !

**Comment by MSaiKiran9** [comment]
Hi @FlorentLvr I updated the pr and wrote some edge cases like exception handling for the same . Here are the final refs : 
init_01
init_02

Hope it's consistent with the existing templates now

**Pull request merged**
