### PR TITLE
Pickle save JSON

### PR DESCRIPTION
**Pull request by kaushalkrishna2000**
Hello @FlorentLvr @jravenel @Dr0p42 @srini047 

Could you review the notebook ?

Thank you

### CODE REVIEW

**Review by srini047 — APPROVED** [review]
LGTM🚀

**Comment by kaushalkrishna2000** [comment]
Should I merge this pull request ?

**Comment by srini047** [comment]
> Should I merge this pull request ?

Nope @kaushalkrishna2000 Waiting for @FlorentLvr or @jravenel for final go through.

**Comment by FlorentLvr** [comment]
@kaushalkrishna2000, it's good now! Thank you for your contribution! I just changed the name of your notebook as we want to have first the tool/package/category (here "Python") and then an action verb describing what the notebook is doing (in your case it's "Save dict to pickle" and not json. Otherwise, it's great! 
Maybe you could do the same notebook to read a pickle file? 🙏

**Pull request merged**
