### PR TITLE
feat: OWID - Add notebook to visualize oil consumption

### PR DESCRIPTION
**Pull request by makingsurgeon**
This PR resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1877

### CODE REVIEW

**Comment by jravenel** [comment]
Hey @makingsurgeon thanks for the good work! We are getting close to the OWID ref: 
Screenshot 2023-06-20 at 21 57 09

I made a few adjustments: 
- added OWID ref
- added import os
- added padding to chart
- changed title to fit OWID ref
- changed subtitle to fit OWID ref
- added value by default to fit OWID ref

Now it looks like this: 
Screenshot 2023-06-20 at 22 12 32

if you can figure out a few more items that would be awesome:
- dotted lines
- no background
- more height (600 maybe)
- the time slider
- change tab name to “Oil consumption”

What do you think?

**Comment by jravenel** [comment]
> Let's keep these for now. I do have some questions, though:
> 
> 
> 
> - What do you mean by "no background"? Do you want a white canvas as opposed to the grey grid right now?
Yes 

> 
> - What do you mean by "more height"? And what unit are we talking about?
The graph should have more height so the curves are more visible see the difference with OWID example 

> 
> - Where is the "tab name" that you are referencing? 
The browser tab is named "Dash"


> 
> Thank you for your feedback, btw!
Welcome 🙏 

Do you think you can work on those improvements?

**Comment by makingsurgeon** [comment]
I have already pushed the changes in the latest push.

**Comment by makingsurgeon** [comment]
Is the newest okay to be pushed? If so, then can we talk about the next steps? Mainly what sort of data should we be looking at next?

**Review by jravenel — COMMENTED** [review]
I have pushed a new commit to make sure it works fine.
- "r" → "url" when reading excel 
- some commas missing 
- slider moved to bottom of chart.

cc @makingsurgeon

**Pull request merged**
