### PR TITLE
Added dynamic link on label click plotly chart python

### LINKED ISSUE #1249: Dash Plotly - Add dynamic link on label click on plotly chart python
I would like to be able to click on the label displayed on my horizontal barchart in Plotly / Dash Plotly: 
https://stackoverflow.com/questions/25148462/open-a-url-by-clicking-a-data-point-in-plotly

- Input
App setup

- Model
Create plotly graph
Create a Dash app with Plotly graph
Setup callback

- Output
Display app

Start from awesome-notebooks template: https://github.com/jupyter-naas/awesome-notebooks/blob/master/Dash/Dash_Deploy_app_in_Naas.ipynb

### PR DESCRIPTION
**Pull request by oguzakif**
Input:
✔️ App setup

Model:
✔️ Create plotly graph
✔️ Create a Dash app with Plotly graph
✔️ Setup callback

Output:
✔️ Display app

This PR closes #1249

### CODE REVIEW

**Comment by oguzakif** [comment]
Hi, I have opened the pr again this branch as you requested. Thank you for your feedback!

**Comment by FlorentLvr** [comment]
@oguzakif, TY for your contribution! 
I tried to click on a label but nothing happen on Dash. The error below appears in the log.
Can you reproduce it?

image

**Comment by oguzakif** [comment]
> @oguzakif, TY for your contribution! I tried to click on a label but nothing happen on Dash. The error below appears in the log. Can you reproduce it?
> 
> image

Thank you! I fixed the given error. The problem was missed condition in callback function. Also fixed the problem of new tab not opening with client-side callback. (Btw these problems were in naas. I didnt encounter them in my local computer)

**Comment by FlorentLvr** [comment]
> > @oguzakif, TY for your contribution! I tried to click on a label but nothing happen on Dash. The error below appears in the log. Can you reproduce it?
> > image
> 
> Thank you! I fixed the given error. The problem was missed condition in callback function. Also fixed the problem of new tab not opening with client-side callback. (Btw these problems were in naas. I didnt encounter them in my local computer)

TY @oguzakif ! It's working well now :) 🍾

**Pull request merged**
