### PR TITLE
Twilio: Send SMS for Google Calendar events

### PR DESCRIPTION
**Pull request by srini047**
Fixes: #904 

[Demo](https://youtu.be/OTFttitlN3E)

### CODE REVIEW

**Comment by Dr0p42** [comment]
No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by srini047** [comment]
Tagging @FlorentLvr

**Comment by FlorentLvr** [comment]
> Tagging @FlorentLvr

@srini047, as we talked about it  on Slack, I think we should create a SMS notifications when an event starts on Google Calendar. Once the notebook "Google Calendar - List events" will be validated. Could you readapt your script to this need and use scheduler to create the alert ? Let me know if you need some guidance on it. 🙏

**Review by FlorentLvr — CHANGES_REQUESTED** [review]
Update connect method to Google Calendar to be able to schedule notebook

**Comment by srini047** [comment]
> > num
> 
> @srini047, just checking your code now. Is there a way to get a validation token without clicking on the link ? This method is working but can not be used if we want to schedule notebooks. :(
> 
> image

Actually, the authorization code is the same every time. I haven't tried that directly but I could give it a try. In case that works then we are good to go.

**Comment by srini047** [comment]
> Update connect method to Google Calendar to be able to schedule notebook

@FlorentLvr Can you provide more insights on this? I can't get it.

**Comment by FlorentLvr** [comment]
> > Update connect method to Google Calendar to be able to schedule notebook
> 
> @FlorentLvr Can you provide more insights on this? I can't get it.

@srini047, sure! To run the notebook, authentication is required. You can do this by clicking on the Google link and then copying and pasting the token provided. However, this method can not be used for scheduling the notebook. Does that clarify things?

**Comment by srini047** [comment]
> > > Update connect method to Google Calendar to be able to schedule notebook
> > 
> > 
> > @FlorentLvr Can you provide more insights on this? I can't get it.
> 
> @srini047, sure! To run the notebook, authentication is required. You can do this by clicking on the Google link and then copying and pasting the token provided. However, this method can not be used for scheduling the notebook. Does that clarify things?

Sure. Makes sense.

**Comment by FlorentLvr** [comment]
@srini047, LGTM 🚀 
This notebook can not be scheduled but work when we ran it. 👍

**Pull request merged**
