### PR TITLE
added python notebook to find phone number in a string

### LINKED ISSUE #1216: Python - Find phone number in string
The objective is to create a template using [Naas IMO framework](https://github.com/jupyter-naas/awesome-notebooks#what-is-the-objective-of-this-repository-) inspired by the code on this link https://github.com/hastagAB/Awesome-Python-Scripts/blob/master/Find-PhoneNumber-in-String/Find-PhoneNumber-in-String.py

### PR DESCRIPTION
**Pull request by anastazir**
> ### Why:
> Closes #1216 
> 
> ### What's being changed:
> added Python notebook to find phone number in a string

### CODE REVIEW

**Comment by FlorentLvr** [comment]
Hi @anastazir! 
TY for your contribution! I tried your notebook using a sentence with a french number and your script did not get it. (i.e below)
Is your script only working for US numbers?

image

**Comment by FlorentLvr** [comment]
> @anastazir did you get a chance to look at @FlorentLvr's feedback? @FlorentLvr can you provide the sentence you used for @anastazir to reproduce?

My sentence was on the screenshot above: """ Mon numéro est le suivant 0606060606 """.
@anastazir, if it's only for US numbers, it's fine. We will just rename the notebook and the description 👍 
Let me know if you need my help!

**Comment by anastazir** [comment]
So the reason the script was not working was because it was designed only to identify number of type XXX-XXX-XXXX.
I have updated it and now it works for both XXX-XXX-XXXX and XXXXXXXXXX.

Capture

Capture1

**Comment by FlorentLvr** [comment]
@anastazir! TY for your contribution! Just added a condition to manage the country code before the number and it works! 🙏

**Pull request merged**
