### PR TITLE
feat: Dash - Interactive plot

### PR DESCRIPTION
**Pull request by makingsurgeon**

### CODE REVIEW

**Comment by Dr0p42** [comment]
No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by FlorentLvr** [comment]
Hi @makingsurgeon! Thank you for your contribution. I tried to run your code but i had the following error while reading your csv path. Can you create an example with a URL path instead of local? 
I also made some change to make your dash working in naas.
Please let me know if you have any questions,

image

**Comment by makingsurgeon** [comment]
Well, @FlorentLvr, to run this example you have to download the the file locally because I tried very hard to find the url where owid keeps the datasets. Unfortunately, I can't find the urls to those csvs. So I don't know if I should do another example that can be done by loading datasets from url instead of loading datasets locally.

**Comment by FlorentLvr** [comment]
> Well, @FlorentLvr, to run this example you have to download the the file locally because I tried very hard to find the url where owid keeps the datasets. Unfortunately, I can't find the urls to those csvs. So I don't know if I should do another example that can be done by loading datasets from url instead of loading datasets locally.

Hey @makingsurgeon! 
Thank you for your feedback! Adding an example with external data will be the best way to make your notebook self-sustaining and executable by anyone :)

**Comment by makingsurgeon** [comment]
Hi, @FlorentLvr, I substituted the example in the original notebook with a new one from owid. The data used in this example can be obtained via a URL. Thank you for your support!

**Comment by FlorentLvr** [comment]
> 

@makingsurgeon! Amazing, I made a few changes and it's all good! Thank you for your contribution 🙏

**Pull request merged**
