### PR TITLE
Trello - Update Cards

### PR DESCRIPTION
**Pull request by Benjifilly**
tell me if you want more update option

## What does this PR do?
It update a target card, it can change the title, description, due and the position

### CODE REVIEW

**Comment by srini047** [comment]
@FlorentLvr  Can you test this?

image

I fear that I'm missing something silly. Unable to track down that.

**Comment by Benjifilly** [comment]
Yea sure no problem

**Comment by Benjifilly** [comment]
I'll check this don't worry

**Comment by Benjifilly** [comment]
> @FlorentLvr Can you test this?
> 
> image
> 
> I fear that I'm missing something silly. Unable to track down that.

It worked for me, I have no problem, the 401 error is usually an authentication error.

**Comment by FlorentLvr** [comment]
> > @FlorentLvr Can you test this?
> > image
> > I fear that I'm missing something silly. Unable to track down that.
> 
> It worked for me, I have no problem, the 401 error is usually an authentication error.

It's all good on my side! I juste created new issues for you @Benjifilly!

**Comment by Benjifilly** [comment]
Ok thanks

**Pull request merged**
