### PR TITLE
Convert CSV URL file to Excel file format

### PR DESCRIPTION
**Pull request by Sophyia7**
I added a code that converts .csv url file to .xlsx(Excel) file.

### CODE REVIEW

**Comment by jravenel** [comment]
Hi @Sophyia7 thanks for the PR, I have small issues with the notebook that I've attached: 

1/ It's not self sustaining in the sense that you cannot test it by itself.
I would suggest to put as input variable a csv that already is available from the internet and then the notebook will be easy to execute. 
For example: 

```
# Declare the input CSV (ex: COVID CSV dataset available on GitHub)
csv_input = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv',"

# Name the XSL spreasheet needed as an output
excel_output = 'covid_dataset.xls' 
```

2/ There is a typo in the section read csv (sept vs sep) and I would put this argument in quotes + add mention that you could change the value of the separator 

`The `sep` argument helps to seperate the rows. It might be a `,` or a `;` and also, ensure the CSV link ends with a CSV file extension.`

3/ the output is throwing an error : 
`FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
convert_csv.to_excel(excel_output, index=False, header=True)`

I think you should add in the input section a '### Import libraries" an do a `pip install openpyxl` but it would likely mean changing the code as well. 

Hope my comments are helpful and that you are able rework, let me know

**Comment by Sophyia7** [comment]
On it, thanks for clarifying things.

**Comment by Sophyia7** [comment]
@jravenel I have made some changes. Waiting for your feedback, thanks.

**Comment by FlorentLvr** [comment]
@Sophyia7! TY for your contribution 👍 
Just made some changes and it's working well. I removed the installation of packages openpyxl and xlwt because they were not used in your notebook. The Pandas library is doing the job pretty well :)

**Comment by Sophyia7** [comment]
Thank you.

**Pull request merged**
