### PR TITLE
Included FFMPEG folder with dynamic graph videos notebook

### LINKED ISSUE #272: ffmpeg - make dynamic graph videos
Following Thom Ives, Ph.D. [post on Linkedin](https://www.linkedin.com/feed/update/urn:li:activity:6875488520111312896/?commentUrn=urn%3Ali%3Acomment%3A(activity%3A6875488520111312896%2C6875494403604131840)&replyUrn=urn%3Ali%3Acomment%3A(activity%3A6875488520111312896%2C6875495625300033536)), the idea is to be able to generate dynamic graph videos with a generic notebook template. 

To be developped.

### PR DESCRIPTION
**Pull request by Neelaksh-Singh**
This PR closes #272. It contains the template for dynamic graph videos generation, wherein the user can give his data points and see their plot turn into the image which then is stitched and converted into video.

### CODE REVIEW

**Comment by FlorentLvr** [comment]
@Neelaksh-Singh, TY for your contribution. 
I didn't succeed to run the script. I was stuck at the first cell (please see screenshot below).
Could you please document the process to help me to go through this notebook ?
TY very much.

image

**Comment by Neelaksh-Singh** [comment]
As per my conversation with @jravenel [here](https://github.com/jupyter-naas/awesome-notebooks/issues/272#issuecomment-999273802), the first block is only needed when one doesn't have those packages or wants to create one own's dataset.

**Comment by Dr0p42** [comment]
> As per my conversation with @jravenel [here](https://github.com/jupyter-naas/awesome-notebooks/issues/272#issuecomment-999273802), the first block is only needed when one doesn't have those packages or wants to create one own's dataset.

Hello @Neelaksh-Singh, `sudo` and `apt-get` are not available in app.naas.ai. Did you tested your notebook on our platform?

We had to use ffmpeg in the past and were using a pre compiled binary that we downloaded.

Sadly, you should offer another way of installing your dependencies for now.

**Comment by Dr0p42** [comment]
Should we close this pull request for now?

**Pull request closed without merging**
