### PR TITLE
feat: Google Play Store - Reviews Sentiment Analysis with Obsei

### PR DESCRIPTION
**Pull request by lalitpagaria**
To complete https://github.com/jupyter-naas/awesome-notebooks/issues/185

### CODE REVIEW

**Comment by lalitpagaria** [comment]
@jravenel @jupyter-naas/core-team Kindly review this PR

**Review by jravenel — COMMENTED** [review]
Hello @lalitpagaria, thanks for your contribution, below my comments: 
- Title of file and Title in notebook were not same → I amended
- added -- user to install `!pip install git+git://github.com/obsei/obsei@master --user`
- at install I have a list of ERROR from pip's dependency resolver → I left the output in my commit so you can seen, I managed to install at the end of the day but this can be a show stopper for people willing to test
- I launched the example of Gmail and did not see the columns : 
app name | time | rating | review | positive | negative
-- | -- | -- | -- | -- | --

I thought there was more column to map certain kind of feedbacks, that we could choose from input section. Did you delete them voluntarily?

- I tried to change the Gmail example to Spotify and extended reviews to 30, it worked well but also saw that negative values are shown as positive. I guess an additional score column from -1 to 1 will be more understandable.

Hope my feedback is clear enought. Feel free to share you views here.

+ At commit we also use the conventional commit convention: https://docs.naas.ai/contributing-to-naas#commit-convention → hence this commit shoud be "feat:  ......."

**Comment by lalitpagaria** [comment]
@jravenel Thanks for review feedback.
It seems file got deleted, I am not seeing any file in this PR now. I have recovered old changes and added your comments about file name and user flag in pip install.

Regarding your other comment please see inline, I need your input out it -

> at install I have a list of ERROR from pip's dependency resolver → I left the output in my commit so you can seen, I managed to install at the end of the day but this can be a show stopper for people willing to test

I also seen it, it seems some obsei's dependencies are conflicting with naas drivers package dependencies. Is there any way to install obsei in virtual environment? I am not well verse with jypiter notebooks hence asking.

> I launched the example of Gmail and did not see the columns :
> app name | time | rating | review | positive | negative
> -- | -- | -- | -- | -- | --

By default Obsei fetch 1 hour old reviews. And if it not able to fetch then we get's empty Dataframe. What do you think about adding `lookup_period` parameter and console print when no review fetched.

> I thought there was more column to map certain kind of feedbacks, that we could choose from input section. Did you delete them voluntarily?

Yes I removed it as better to keep this in two separate notebooks as both require different set of parameters. Please suggest if you like to have both in same notebook.

> I tried to change the Gmail example to Spotify and extended reviews to 30, it worked well but also saw that negative values are shown as positive. I guess an additional score column from -1 to 1 will be more understandable.

I will change sentiment probabilities to polarities.

**Comment by jravenel** [comment]
Hello Lalit, 

Sorry for the delay in reply, after discussion: 
→ virtual environment: no as we need to keep the docker-machine simple: better to install obsi inside naas_drivers maybe : what do you think?
→ adding `lookup_period` or even better `date_from`, `date_to` would provide huge benefits.
→ Yes better for us to have everything in the same notebook to ensure the attention of the user and focus.


🤙 Is that ok for you @lalitpagaria ?
Feel free to ask if you need any help.

**Comment by Dr0p42** [comment]
Closing for inactivity.

**Comment by jravenel** [comment]
@lalitpagaria is there something we should retry?

**Comment by lalitpagaria** [comment]
@jravenel Unfortunately I will not get time to work on it.
In the future, in Obsei we are planning to manage dependency properly (ie minimally) hence it may cause less conflict.
Till then let's close this and if someone from the community like to work on it then they may refer to this PR as a reference.
WDYT?

**Comment by jravenel** [comment]
> @jravenel Unfortunately I will not get time to work on it. In the future, in Obsei we are planning to manage dependency properly (ie minimally) hence it may cause less conflict. Till then let's close this and if someone from the community like to work on it then they may refer to this PR as a reference. WDYT?

Very well, got it @lalitpagaria. Then. let's close this PR for now and feel free to let us know once you think we can resume.

**Pull request closed without merging**
