### PR TITLE
feat: first commit to improve the template on naming

### PR DESCRIPTION
**Pull request by jravenel**
changed filename, title, desc, tags

### CODE REVIEW

**Comment by jravenel** [comment]
@SuhasBRao following my comment on the original issue, let's try to improve the template :)

**Review by SuhasBRao — APPROVED** [review]
@jravenel I see you have deleted the old file, We will create a new file that allows us to solve the issue.

**Comment by jravenel** [comment]
> @jravenel I see you have deleted the old file, We will create a new file that allows us to solve the issue. 

@SuhasBRao No I just renamed it

**Comment by SuhasBRao** [comment]
Yes, I'm working on that file itself but on a new branch

**Comment by jravenel** [comment]
Ok ok did you just sent an update via email? I received something with -15days

**Comment by SuhasBRao** [comment]
Yes that's the updated content as required 😊

**Comment by jravenel** [comment]
Hey, did you push the updates to master?

**Comment by SuhasBRao** [comment]
Yes I pushed those changes,.
Did you get that email that was triggered by notebook.

**Comment by jravenel** [comment]
yep @SuhasBRao will review by tmrw and publish

**Pull request merged**
