### PR TITLE
Adding generate weekly newsletter notebook

### PR DESCRIPTION
**Pull request by SuhasBRao**
The notebook allows you to create a weekly newsletter based on Issue/Pr activity for a GitHub repository. The content of the newsletter can be modified as per needs.
Here's a snapshot of the content, 

Screenshot from 2022-10-09 19-26-59

### CODE REVIEW

**Comment by FlorentLvr** [comment]
@SuhasBRao, as you are still discussing on the issue with @jravenel, let me know when I can review your PR here :)

**Comment by SuhasBRao** [comment]
> @SuhasBRao, as you are still discussing on the issue with @jravenel, let me know when I can review your PR here :)

Sure

**Comment by FlorentLvr** [comment]
@SuhasBRao! Thank you for your contribution! You did amazing work 💯 🥇 !
Just reworked your code structure a bit and add markdown to document the full process :)
It's all good :). @jravenel, what do you think?

**Comment by SuhasBRao** [comment]
> @SuhasBRao! Thank you for your contribution! You did amazing work 100 1st_place_medal ! Just reworked your code structure a bit and add markdown to document the full process :) It's all good :). @jravenel, what do you think?

Thank you @FlorentLvr, I removed **get_open_issues** function which was written only for testing purposes,

**Pull request merged**
