### PR TITLE
feat: bitly create links

### PR DESCRIPTION
**Pull request by FlorentLvr**

### CODE REVIEW

**Comment by Dr0p42** [comment]
No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Review by srini047 — COMMENTED** [review]
@FlorentLvr  The code looks fine to me. But I cannot generate a Bitly access token to verify explicitly. Other than that we are good to go.

**Comment by FlorentLvr** [comment]
> @FlorentLvr The code looks fine to me. But I cannot generate a Bitly access token to verify explicitly. Other than that we are good to go.

@srini047! You can create a free account and test it then: https://bitly.com/pages/landing/free-plan
Can you try it please ? 🙏

**Comment by srini047** [comment]
@FlorentLvr As mentioned I did create a free account and then landed here.

Screenshot 2023-02-20 at 7 10 20 PM

When I click generate token it says password is required. But I signed up using Google OAuth. Any help to generate access token is appreciated.

**Comment by FlorentLvr** [comment]
> @FlorentLvr As mentioned I did create a free account and then landed here.
> 
> Screenshot 2023-02-20 at 7 10 20 PM
> 
> When I click generate token it says password is required. But I signed up using Google OAuth. Any help to generate access token is appreciated.

Hi @srini047! You try it as well and I had to reset my password manualy to generate the token. Can you try it as well and let me know if it works?

https://support.bitly.com/hc/en-us/articles/230647907-How-do-I-generate-an-OAuth-access-token-for-the-Bitly-API-
image

**Comment by srini047** [comment]
@FlorentLvr Just generated the token as per instructions. It worked smoothly.

I'm merging it🚀

**Review by srini047 — APPROVED** [review]
@FlorentLvr Just generated the token as per instructions. It worked smoothly.

I'm merging it🚀

**Pull request merged**
