### PR TITLE
john hopkins data_plotly world map

### PR DESCRIPTION
**Pull request by krishkatyal**
i tried my best to merge these 2 notebooks but there is some issue in the data pls check it out.

### CODE REVIEW

**Comment by jravenel** [comment]
Hello there, can you brief me on the issue more precisely with screenshots please ? @krishkatyal

**Comment by jravenel** [comment]
That's because they don't have the same schema (headers) apparenlty.  If this is the case you need to preprocess the data so the concat works.

**Comment by krishkatyal** [comment]
> That's because they don't have the same schema (headers) apparenlty. If this is the case you need to preprocess the data so the concat works.

i'll try to do that.

**Comment by jravenel** [comment]
Basically you. need 3 columns: 
- DATE 
- COUNTRY 
- VALUE : number of active cases 

But right now the columns are countries.
When you have that you can build the mapchart easy.

**Comment by jravenel** [comment]
@krishkatyal checking in.  Do you need help?

**Comment by krishkatyal** [comment]
> @krishkatyal checking in. Do you need help?

sorry, I've been preoccupied, I will complete my task soon.

**Comment by krishkatyal** [comment]
I think that I will need to create a custom function for this but I've not worked with pandas enough to do this, can u help me as to what will be the code?

**Comment by jravenel** [comment]
Hi @krishkatyal I will check if someone in the community can help.

**Comment by RedaAllab** [comment]
@jravenel @jravenel
Hello guys ! I made the necessary changes to make this template work.
Please check it.

**Comment by jravenel** [comment]
@RedaAllab thanks a lot, I tested it and it worked. 
@krishkatyal check out the work of @RedaAllab for learning :) and let's discuss if you want to do another topic. We have a lot going in the world open data "sea" 🌊✅

**Comment by krishkatyal** [comment]
I have viewed the code, I wasn't familiar with dataprep but I completely understand it now. I am learning a lot by doing open source work, really looking forward to doing more work @jravenel 

Thanks :)

**Comment by jravenel** [comment]
> I have viewed the code, I wasn't familiar with dataprep but I completely understand it now. I am learning a lot by doing open source work, really looking forward to doing more work @jravenel
> 
> Thanks :)

Great! Stay tuned on the issues, we want to build more open data templates.

**Pull request merged**
