### PR TITLE
Python - Copy files and subdir from directory to another directory

### PR DESCRIPTION
**Pull request by hitchhicker007**
Tags: #python #os #shutil #operations #snippet

**Author:** [Parth Panchal](https://www.linkedin.com/in/parthpanchal8401/)

### CODE REVIEW

**Comment by Dr0p42** [comment]
No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by FlorentLvr** [comment]
> @FlorentLvr what should I do now?

@hitchhicker007, I am checking now! I think there is a misunderstanding :). Your file should be names and stored according to the issue:
Python - Copy files and subdir from directory to another directory

So:
Folder: Python
Name: Python_Copy_files_and_subdir_from_directory_to_another_directory.ipynb

No worry, i will update it!

Hope it is more clear for you now

**Comment by FlorentLvr** [comment]
> got it. Thanks @FlorentLvr

@hitchhicker007, I just push some changes! It's working perfectly! TY for your contribution! Could you add your name and linkedin URL in the Author section? Then, I will merge your PR 👍 

image

**Comment by hitchhicker007** [comment]
@FlorentLvr I added my name and linkedin URL, can you verify it?

**Comment by FlorentLvr** [comment]
> @FlorentLvr I added my name and LinkedIn URL, can you verify it?

Did you push your changes? You need to pull my changes and then push yours.

**Comment by hitchhicker007** [comment]
@FlorentLvr I did it. Please check.

**Comment by hitchhicker007** [comment]
@FlorentLvr Can you please merge my PR?

**Comment by FlorentLvr** [comment]
Hi @hitchhicker007! Just merged it! TY for your contribution :).

**Pull request merged**
