### PR TITLE
feat: added Cloud-Mercato VM pricing first commit

### PR DESCRIPTION
**Pull request by jravenel**
@ZuluPro youhouuu, I will let you keep working on it :)

### CODE REVIEW

**Comment by FlorentLvr** [comment]
Hi @ZuluPro! Thank you for your contribution! I tried to run the code but I add the below error.
What kind of file are you returning? If it's a csv, you should use this syntax:

`res = requests.get('https://p2p.cloud-mercato.com/flavors/csv', params=params)`
`df = pd.read_csv(res.content)`

Let me know if you need help!

image

**Comment by FlorentLvr** [comment]
Hi @ZuluPro! Just checked your PR and it's working well! TY!
However, I saw you added a Token as a parameter:
-> Would it be possible to have a procedure to get it? 
-> What is the limit for anonymous users?

**Comment by FlorentLvr** [comment]
> Hi @ZuluPro! Just checked your PR and it's working well! TY! However, I saw you added a Token as a parameter: -> Would it be possible to have a procedure to get it? -> What is the limit for anonymous users? Let me know if you need my help :)

As talked about it together, I proposed to add this text to improve clarity for users below "Setup Variables":
- [Create your token]([graphql.cloud-mercato.com](http://graphql.cloud-mercato.com/))
- You can access data without a token but you are limited to 3 requests/days
- Get a paid account to have access to VM with +16 CPUs

**Comment by jravenel** [comment]
Hey @ZuluPro is that normal that you have only 10 lines in the data set queried by default? 

Screenshot 2022-11-01 at 01 02 02

**Comment by jravenel** [comment]
je valide comme c'est pas lié au notebook je pense

**Pull request merged**
