### PR TITLE
BigQuery Connector

### PR DESCRIPTION
**Pull request by MinuraPunchihewa**
Added a connector module for establishing a connection with BigQuery and templates for reading tables and creating tables using a CSV file.

This was inspired by the Snowflake templates available already.

@jravenel Let me know if this is useful and I can create a few other templates similar to what has already been done for Snowflake.

### CODE REVIEW

**Comment by Dr0p42** [comment]
No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by jravenel** [comment]
As mentionned in Issue @MinuraPunchihewa  a video recording of how it works live would be amazing.

**Comment by jravenel** [comment]
add @Dr0p42 as reviewer.

**Comment by MinuraPunchihewa** [comment]
@jravenel I should be able to do that. You want a casual recording of this running locally for you guys to view?

**Comment by jravenel** [comment]
> @jravenel I should be able to do that. You want a casual recording of this running locally for you guys to view?

Better if it's from Naas as it's the env we are going to test in.

**Comment by MinuraPunchihewa** [comment]
@jravenel Alright, let me see what I can do.

**Comment by FlorentLvr** [comment]
@MinuraPunchihewa @jravenel, just checked your notebooks and it is all good! 
Did you have time to do the video?

**Comment by MinuraPunchihewa** [comment]
@FlorentLvr Sorry, I have not been able to get around to doing it yet. I will look into doing this over the weekend. Sorry for the delay.

**Pull request merged**
