### PR TITLE
feat: Pandas loop

### PR DESCRIPTION
**Pull request by OketunjiOludolapo**
A notebook to loop over dataframes

### CODE REVIEW

**Comment by jravenel** [comment]
Hello @OketunjiOludolapo, your notebook name does not respect naming convention. 
Could you please make the necessary correction? Here is the issue, I also have create a link here.

**Comment by jravenel** [comment]
Hello @OketunjiOludolapo, following our conversation yesterday. Here is the contribution guidelines : https://docs.naas.ai/contributing-to-naas

**Comment by OketunjiOludolapo** [comment]
> Hello @OketunjiOludolapo, following our conversation yesterday. Here is the contribution guidelines : https://docs.naas.ai/contributing-to-naas
> 
> You need to start the commit/PR with "feat:" for example

Thanks. i will r=edit and recommit it

**Comment by jravenel** [comment]
great, you also don't need to run the generateReadme anymore, the CI is
doing it.

**Comment by OketunjiOludolapo** [comment]
i've made the changes. pls review

**Pull request merged**
