### PR TITLE
Open Ai - text based prediction

### PR DESCRIPTION
**Pull request by Mohwit**
Please, have a look and suggest changed, if any required. Thanks!

### CODE REVIEW

**Comment by Dr0p42** [comment]
No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by Mohwit** [comment]
https://www.loom.com/share/6298fa3497d54af0a5967b40c0f20d50

Sharing loom, as discussed!

**Review by srini047 — APPROVED** [review]
LGTM🚀

**Comment by srini047** [comment]
@Mohwit Next time try to use the [naas.secret](https://docs.naas.ai/features/secret) feature for storing the API_KE or secrets.

**Comment by Mohwit** [comment]
@srini047 Surely, will take care of that.

**Pull request merged**
