### PR TITLE
fix: Added generic ffmpeg package helper and updated sample wav file

### LINKED ISSUE #2310: Python[Convert audiofile from wav to mp3] - Download ffmpeg mv command is failing due to newer version
**Describe the bug**
Wget commands in the download ffmpeg gives the newer version binary but there is a static version tied to mv command which makes the notebook prone to failure.

**To Reproduce**
1. Go to 'awesome-notebooks/Python/Python_Convert_audiofile_from_wav_to_mp3'
2. Click on 'run'
3. Scroll down

**Expected behavior**
The notebook should convert the wav to an mp3 file as expected.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by YellowFoxH4XOR**
## Fixes

This PR resolves #2310

## What does this PR do?
Added a function to identify the new ffmpeg binary and move it accordingly. Also updated the example wav file as the older one was not found.

## Screenshots
Provide supporting docs, limitations if any, video of the template, or anything that you want to share to support your PR
image

### CODE REVIEW

**Review by srini047 — COMMENTED** [review]
- [x] Reorder the cells, since I see the `find_directory_starting_with_ffmpeg_git ` well before the import libraries. And the `find_directory_starting_with_ffmpeg_git ` must come under the `Model` section.
- [ ] You could add `*.xz` in the `.gitignore` to keep the git commit clean.
- [ ] Add your name besides in the `Author: ` cell

**Comment by YellowFoxH4XOR** [comment]
> * [ ]  Reorder the cells, since I see the `find_directory_starting_with_ffmpeg_git ` well before the import libraries. And the `find_directory_starting_with_ffmpeg_git ` must come under the `Model` section.
> * [x]  You could add `*.xz` in the `.gitignore` to keep the git commit clean.
> * [x]  Add your name besides in the `Author: ` cell

Thanks @srini047  for the review comments. I have addressed them but there is one issue with the first comment as pydub is dependent on ffmpeg so need to append the ffmpeg binary path to the environment variable before importing pydub. I have added proper markdowns for the same.

**Review by srini047 — APPROVED** [review]
LGTM🚀

@FlorentLvr Do have a look if there is anything else to be added or removed.

**Comment by FlorentLvr** [comment]
> LGTM🚀
> 
> @FlorentLvr Do have a look if there is anything else to be added or removed.

Sure! I will try to have a look tonight or tomorrow morning :)

**Pull request merged**
