### PR TITLE
feat: Excel custom sheet

### PR DESCRIPTION
**Pull request by Sebgh83**

### CODE REVIEW

**Comment by Sebgh83** [comment]
Hi @FlorentLvr . I think the script is done. Can you review it please ?

**Comment by FlorentLvr** [comment]
Hi @Sebgh83 ! TY for your contribution. It's working well.
I reworked the structure:
- I put all variables on top => then it's easier to setup and understand
- I used variables instead of string.
=> For example, i set the sheet range as variable. Then it's easier to change.
- I removed useless libraries
I also added a new notebook to get the active range dynamically. I am sure it could help on the future. :)
Could you please have a look and let me know if it's good for you ?

**Review by FlorentLvr — APPROVED** [review]

**Comment by Sebgh83** [comment]
Hi @FlorentLvr, 

Thanks for the edits. I take note of the remarks to improve the next script.

Thank's again, I appreciate it

**Comment by FlorentLvr** [comment]
TY @Sebgh83 and welcome to the community 🥇 

Naas_contrib_step1

**Comment by jravenel** [comment]
Hello @Sebgh83, welcome to the contributor team, do you have 15min so we can record a demo of your template for content creation? Looking forward to it!

**Pull request merged**
