### PR TITLE
feat: added contributor's guide to readme

### PR DESCRIPTION
**Pull request by abrahamalen**
Updated README by adding a link to the contributor's guide notion page.
[issue link](https://github.com/jupyter-naas/awesome-notebooks/issues/1028)

### CODE REVIEW

**Comment by Dr0p42** [comment]
No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by Dr0p42** [comment]
Thank you @abrahamalen for opening this pull request.

@FlorentLvr @jravenel @abrahamalen I am wondering, should we simply put the link in the "How to contribute" section of the README.md and get rid of the steps ? I feel like it will not stay synced between Notion and Github + there are a lot more information on Notion.

What do you think?

**Comment by jravenel** [comment]
This should be on docs.naas.ai and readme

**Comment by Dr0p42** [comment]
I suggested an edit

**Review by abrahamalen — COMMENTED** [review]
Yep, this is what I meant. all good @Dr0p42

**Pull request merged**
