### PR TITLE
Notebook Commit

### PR DESCRIPTION
**Pull request by kaushalkrishna2000**
Hello @FlorentLvr @Dr0p42 @jravenel 
I have made the notebook kindly review it.
The issue is #1357 twitter add a member to list.
Thanks.

### CODE REVIEW

**Comment by kaushalkrishna2000** [comment]
Hello ?

**Comment by kaushalkrishna2000** [comment]
Hello ?

**Comment by jravenel** [comment]
@kaushalkrishna2000 we will come back to you don't worry :) We are quite busy those days sorry.

**Comment by kaushalkrishna2000** [comment]
No problem

**Review by FlorentLvr — CHANGES_REQUESTED** [review]
@kaushalkrishna2000, sorry for the delay.
I did a bit of cleaning because I didn't really understand what was the input needed on top and all cells on model.
I pass the connect but i got this error while trying to add a new member to my list.
Could you please have a look ? 🙏 TY

image

**Comment by kaushalkrishna2000** [comment]
Hello @FlorentLvr ,

There are 2 types of authentication oauth1.0 and oauth2.0 .

The list searching is done using oauth1.0 and member search is done using oauth2.0 .

The oauth1.0 needs read,write permission to do that.

On twitter developer portal , in the app that you made you will need to give read,write permission in user authentication settings.

The you need to go to the keys and token tab and regenerate all the keys and tokens.

The you can use consumer keys and authentication tokens details to log into tweepy to perform the action .

Let me know if you have any problem.

Also you can refer to tweepy docs authentication page to get a clearer picture.

I am planning to do this work solely based on oauth2.0 (might have to do more research on that)

**Comment by FlorentLvr** [comment]
> Hello @FlorentLvr ,
> 
> There are 2 types of authentication oauth1.0 and oauth2.0 .
> 
> The list searching is done using oauth1.0 and member search is done using oauth2.0 .
> 
> The oauth1.0 needs read,write permission to do that.
> 
> On twitter developer portal , in the app that you made you will need to give read,write permission in user authentication settings.
> 
> The you need to go to the keys and token tab and regenerate all the keys and tokens.
> 
> The you can use consumer keys and authentication tokens details to log into tweepy to perform the action .
> 
> Let me know if you have any problem.
> 
> Also you can refer to tweepy docs authentication page to get a clearer picture.
> 
> I am planning to do this work solely based on oauth2.0 (might have to do more research on that)

@kaushalkrishna2000, I regenerate all my credentials from the twitter developer portal and still got the same error.
It is weird because I pass the connect but still have the same error to add new member:

image

**Comment by kaushalkrishna2000** [comment]
Hello @FlorentLvr 
Can you check this stackoverflow ?
https://stackoverflow.com/questions/74436471/errors-when-trying-to-tweet-using-tweepy

**Comment by kaushalkrishna2000** [comment]
Also could you make sure if the secrets are imported correctly ?

**Comment by kaushalkrishna2000** [comment]
Hello @jravenel @Dr0p42 could you try this notebook to see if the same error appear ?

**Comment by kaushalkrishna2000** [comment]
Hello ?

**Comment by FlorentLvr** [comment]
> Hello ?

I am sorry but I didn't manage to make your script work. Did you make it work on your side? Could you please prepare a small video showing how it works? Then I will be able to validate your notebook 🙏

**Comment by FlorentLvr** [comment]
Hi @kaushalkrishna2000!
Since we're still encountering difficulties with this matter, could you create a brief video demonstrating how it functions on your end? This way, I'll be able to merge your pull request. Thank you for your assistance. 🙏

**Comment by kaushalkrishna2000** [comment]
It might take some time to create a video.
image
Could you verify if your oauth1.0 permission looks like this ?

**Comment by FlorentLvr** [comment]
> It might take some time to create a video. image Could you verify if your oauth1.0 permission looks like this ?

Yes, maybe i am wrong about setting the consumer keys, tokens, oauth2... That's why I just wanted to a short video to make sure I didn't do any mistakes on the setting part.

image

**Comment by kaushalkrishna2000** [comment]
Hello @FlorentLvr 

Can you see this video [https://www.youtube.com/watch?v=RvT_X61dJn4](url)
Around the timestamp 2:49 ?

It will tell you to set authentication settings which will enable the oauth tokens to get read and write permission.
After setting the authentication settings you might have to regenerate the tokens .

**Comment by kaushalkrishna2000** [comment]
image
Click on the set up user authentication settings.
You will see this sort of page.
image
image
Set the required permission and then click  on ok.

After this you will have to regenerate all the tokens.

**Comment by kaushalkrishna2000** [comment]
I hope this will solve the problem.

If not the give me some time to make a video.

**Comment by kaushalkrishna2000** [comment]
Hello @FlorentLvr 
Did the previous information help you in achieving the objective ?

**Comment by kaushalkrishna2000** [comment]
Hello @FlorentLvr Were you able to achieve it?

**Comment by FlorentLvr** [comment]
> Hello @FlorentLvr Were you able to achieve it?

Unfortunately, I am still stuck.
@srini047, could you please have a look at this issue?

**Comment by srini047** [comment]
Hey @kaushalkrishna2000 !!
Mind having a small meeting to resolve the issue? The reason is I can't get access to TwitterAPI since my dev account is blocked.

**Comment by kaushalkrishna2000** [comment]
Sure

How about 10.30 pm tonight ?
I am outside now.

**Comment by srini047** [comment]
Here's the link to the meet: [https://meet.google.com/zdh-epnq-pbw](https://meet.google.com/zdh-epnq-pbw)

**Comment by kaushalkrishna2000** [comment]
Hello @jravenel @FlorentLvr @srini047 @Dr0p42 
I have made the necessary changes and also provided with a link to the sample implementation.

Could you make sure that no secret/access_token/password leaks ?

Thank you

Video Link: 
https://drive.google.com/file/d/1LwOW74zpZWV0xdsIsxkL3LRLhliDU7Kn/view?usp=sharing

**Comment by srini047** [comment]
> Hello @jravenel @FlorentLvr @srini047 @Dr0p42 I have made the necessary changes and also provided with a link to the sample implementation.
> 
> Could you make sure that no secret/access_token/password leaks ?
> 
> Thank you
> 
> Video Link: https://drive.google.com/file/d/1LwOW74zpZWV0xdsIsxkL3LRLhliDU7Kn/view?usp=sharing

Sure👍
We will get back to you super soon.

**Comment by jravenel** [comment]
@kaushalkrishna2000 @srini047 @FlorentLvr thanks a lot for keeping the ball moving on this topic!!

**Comment by FlorentLvr** [comment]
> > Hello @jravenel @FlorentLvr @srini047 @Dr0p42 I have made the necessary changes and also provided with a link to the sample implementation.
> > Could you make sure that no secret/access_token/password leaks ?
> > Thank you
> > Video Link: https://drive.google.com/file/d/1LwOW74zpZWV0xdsIsxkL3LRLhliDU7Kn/view?usp=sharing
> 
> Sure👍 We will get back to you super soon.

Thanks for the video @kaushalkrishna2000! It really help me to check :)

**Pull request merged**
