### PR TITLE
2001 gmail mark emails as seen

### PR DESCRIPTION
**Pull request by tony-georgiev**

### CODE REVIEW

**Comment by tony-georgiev** [comment]
@FlorentLvr 
Ready to review

**Comment by FlorentLvr** [comment]
@tony-georgiev, i just reviewed your work. It seems the "get_emails_by_date" function marked emails as seen. Can you confirm? If so, what is the difference between your template and the "Gmail_Get_emails_by_date.ipynb" ?

**Comment by tony-georgiev** [comment]
> @tony-georgiev, i just reviewed your work. It seems the "get_emails_by_date" function marked emails as seen. Can you confirm? If so, what is the difference between your template and the "Gmail_Get_emails_by_date.ipynb" ?

Hey @FlorentLvr ,
I apologise for the inconvenience, it seems that I have made a mistake as I had changed the "get_emails_by_date" template, but it looks like the work hadn't been saved. I have the updated version but I am not sure how to upload it as the template is now in the master branch. In order to fix it I used IMAP libraries as in "Gmail_list_most_interesting".
How should I proceed?

**Comment by tony-georgiev** [comment]
@FlorentLvr 
Fixed the issue and the work is ready to review.

**Pull request merged**
