### PR TITLE
pandasql - Query CSV using SQL

### PR DESCRIPTION
**Pull request by MinuraPunchihewa**
Added the notebook template to query a CSV file using SQL.

Please note that this template requires a previous version of SQLAlchemy: `sqlalchemy==1.4.46`. This is because `pandsql` does not seem to work without this version of the package.

### CODE REVIEW

**Comment by FlorentLvr** [comment]
@MinuraPunchihewa, thank you for your contribution again 🙏 
To make it simplier, I created a fake data frame and select the first column. 
I think maybe you could create more example with SQL query. 
Are you oftenly using pandassql? 
Do you have more use cases to share? 😄

**Comment by MinuraPunchihewa** [comment]
@FlorentLvr Hey, I am not a big user just yet. I just discovered it a little while back. I have been meaning to incorporate it into my workflow when working with files though.
I thought it might be a good idea to add pandasql templates that allow users to query other files types using SQL, such as Excel, Parquet etc.
What do you think?

**Comment by FlorentLvr** [comment]
> @FlorentLvr Hey, I am not a big user just yet. I just discovered it a little while back. I have been meaning to incorporate it into my workflow when working with files though. I thought it might be a good idea to add pandasql templates that allow users to query other files types using SQL, such as Excel, Parquet etc. What do you think?

Yes sure! Do you want me to create new issues?

**Comment by MinuraPunchihewa** [comment]
@FlorentLvr Sure, that sounds good. I can work on them.
I can take up the other OpenAI issues as well. I will need a little more clarity on them though.

**Comment by FlorentLvr** [comment]
> @FlorentLvr Sure, that sounds good. I can work on them. I can take up the other OpenAI issues as well. I will need a little more clarity on them though.

Just created the 2 issues for the next iteration! 
Let's talk directly on the OpenAI issues if you need more clarity. Sounds good?

**Pull request merged**
