### PR TITLE
feat: Added extract chat from whatsapp

### PR DESCRIPTION
**Pull request by Mohwit**

### CODE REVIEW

**Comment by jravenel** [comment]
@Mohwit can you provide update on this ? Can we help ?

**Comment by Mohwit** [comment]
@jravenel I am still waiting for the review, I am done with my part. If there will be any issue I will look into it but for that I need feedback if it's working fine for you guys!

**Comment by FlorentLvr** [comment]
Hi @Mohwit!
I have reviewed your notebook and made several changes to improve its readability and clarity.

In the input section, I have provided a detailed procedure using bullet points to get straight to the point. Additionally, I have included variables' names and descriptions. Since we export the chat manually, the file path should be the first variable. Therefore, I have renamed the other variable to 'group_chat_name' because 'send' was not really accurate. Do you agree with this modification?

In the model section, I have divided your code into two blocks and added markdown explanations. I have also corrected the code's indentation, which was incorrect and displayed in red.

For the output section, I have included more information about the number of messages fetched to provide better insights to the user.

Please let me know if you are satisfied with these changes. If you are, you can merge this pull request; otherwise, I will take care of it by the end of the day.

**Review by FlorentLvr — APPROVED** [review]

**Comment by Mohwit** [comment]
Hey @FlorentLvr, I have checked the changes and they all looks good. So, I have merged the the pr as you said.

**Pull request merged**
