### PR TITLE
feat: github issues driver added

### PR DESCRIPTION
**Pull request by SanjuEpic**
Referring to this issue #435, pending notebook has been updated now 
Thanks!

### CODE REVIEW

**Comment by Dr0p42** [comment]
Hello @SanjuEpic, are you sure your code is working with naas_driver? 

I have the following error:
image

Should we merge a naas driver pr first?

**Comment by SanjuEpic** [comment]
Yes @Dr0p42 it was working on my end, before i raised this PR
Let me check again

**Comment by SanjuEpic** [comment]
It's working on my end, and also the GitHub
 drivers are all already merged a week back
what should we do to clear this problem @Dr0p42 :(

get_issues_from_projects

**Comment by FlorentLvr** [comment]
@SanjuEpic , well done ! Just made some modificatio regarding the order of the bar column. TY for your contribution :)

**Pull request merged**
