### PR TITLE
NBA betting lines template

### PR DESCRIPTION
**Pull request by ja-williams**
@FlorentLvr This is the NBA betting lines template. Please take a look and let me know if I need to change or add anything. I am still not sure how  to change the issue status, so I might need your help with that

### CODE REVIEW

**Comment by Dr0p42** [comment]
Hello @ja-williams,

Thank you for your contribution.

I took a look at your notebook and it seems that it does not respect our conventions (Quite easy to fix). Here is what the CI is saying:
```
 Errors found in: NBA/lines.ipynb
check_naas_logo ... KO 
    Requirements:
        - Cell number: 1
        - Cell type: Markdown
        - Shape: <img width="10%" alt="Naas" 
src="https://landen.imgix.net/jtci2pxwjczr/assets/5ice39g4.png?w=160"/>
    
check_title_match_regexp ... KO 
    Requirements:
        - Cell number: 2
        - Cell type: Markdown
        - Shape: "# something - some other thing"
    
check_tool_tags ... KO 
    Requirements:
        - Cell number: 3
        - Cell type: Markdown
        - Shape: "**Tags:** #atLeastOneTool"
    
check_author ... KO 
    Requirements:
        - Cell number: 4
        - Cell type: Markdown
        - Shape: "**Author:** At least one author name"
    
check_input_title_exists ... KO 
    Requirements:
        - Cell number: Any
        - Cell type: Markdown
        - Shape: "## Input"
    
check_model_title_exists ... KO 
    Requirements:
        - Cell number: Any
        - Cell type: Markdown
        - Shape: "## Model"
    
check_output_title_exists ... KO 
    Requirements:
        - Cell number: Any
        - Cell type: Markdown
        - Shape: "## Output"
```
This output should be quite explicit to help you fix your notebook.

You can take a look at our [template](https://github.com/jupyter-naas/awesome-notebooks/blob/master/template.ipynb) to get an example of what it should looks like.

Let us know if you need more info.

Looking forward to have this nb merged :)

**Comment by ja-williams** [comment]
Hi @Dr0p42 and @FlorentLvr!

I just committed my updated NBA betting lines template to match the conventions of the template. It looks like it is still failing a check though, do you know what the issue is?

**Comment by Dr0p42** [comment]
> Hi @Dr0p42 and @FlorentLvr!
> 
> I just committed my updated NBA betting lines template to match the conventions of the template. It looks like it is still failing a check though, do you know what the issue is?

Hello @ja-williams, awesome 👍

The CI is complaining because you left the lines_old.ipynb notebook. I will remove it and see how it goes but we should be good I think.

**Comment by Dr0p42** [comment]
@FlorentLvr can you review this pull request when you have some time please? :)

**Comment by FlorentLvr** [comment]
@ja-williams ! TY for your contribution :). 
You did an amazing work and I was also happy to work one my favorite passion 🏀.
I made some changes on your notebook to fit to our standard (folder name = source => Draft Kings) + I created an email to received the moneyline. 
Can you please check it and make some changes if needed ? 
Don't hesitate to ask any question !
If it's good, I will merged the PR then :)

**Comment by ja-williams** [comment]
@FlorentLvr Those changes all look great, the email feature is awesome!
The notebook looks good to go on my end, and I can't wait to see it merged into awesome-notebooks.
Thanks for all the help on this too!

**Pull request merged**
